//////////////////////////////////////////////////////////////////////////
//
//  Copyright (c) 2007-2008, Image Engine Design Inc. All rights reserved.
//
//  Redistribution and use in source and binary forms, with or without
//  modification, are permitted provided that the following conditions are
//  met:
//
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//
//     * Neither the name of Image Engine Design nor the names of any
//       other contributors to this software may be used to endorse or
//       promote products derived from this software without specific prior
//       written permission.
//
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
//  IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
//  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
//  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
//  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
//  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
//  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
//  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
//  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
//  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//////////////////////////////////////////////////////////////////////////

IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( BoolData, bool );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( FloatData, float );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( DoubleData, double );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( IntData, int );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( UIntData, unsigned int );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( CharData, char );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( UCharData, unsigned char );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( HalfData, half );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( ShortData, short );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( UShortData, unsigned short );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( Int64Data, int64_t );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( UInt64Data, uint64_t );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( V2iData, int );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( V3iData, int );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( V2fData, float );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( V3fData, float );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( V2dData, double );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( V3dData, double );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( Color3fData, float );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( Color3dData, double );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( Color4fData, float );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( Color4dData, double );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( Box2iData, int );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( Box3iData, int );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( Box2fData, float );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( Box3fData, float );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( Box2dData, double );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( Box3dData, double );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( M33fData, float );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( M33dData, double );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( M44fData, float );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( M44dData, double );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( QuatfData, float );
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION( QuatdData, double );

