##########################################################################
#
#  Copyright (c) 2007, Image Engine Design Inc. All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are
#  met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#
#     * Neither the name of Image Engine Design nor the names of any
#       other contributors to this software may be used to endorse or
#       promote products derived from this software without specific prior
#       written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
#  IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
#  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
#  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
#  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
#  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
#  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
#  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
#  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
#  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
##########################################################################

import os
import IEEnv

import VersionControl
VersionControl.setVersion( "IEBuild", "1.5.5" )
import IEBuild

version = "0.5.0"
coreMajorVersion = "2"
openEXRVersion = "1.4.0"
boostVersion = "1.33.1"
pythonVersion = "2.5"
glewVersion = "1.4.0"

libSources = [
	"src/IECoreGL.cpp",
	"src/State.cpp",
	"src/Primitive.cpp",
	"src/PointsPrimitive.cpp",
	"src/DiskPrimitive.cpp",
	"src/QuadPrimitive.cpp",
	"src/SpherePrimitive.cpp",
	"src/MeshPrimitive.cpp",
	"src/BoxPrimitive.cpp",
	"src/Renderable.cpp",
	"src/Bindable.cpp",
	"src/Group.cpp",
	"src/Camera.cpp",
	"src/Texture.cpp",
	"src/Scene.cpp",
	"src/Exception.cpp",
	"src/NumericTraits.cpp",
	"src/Shader.cpp",
	"src/Window.cpp",
	"src/StateComponent.cpp",
	"src/TypedStateComponent.cpp",
	"src/Renderer.cpp",
	"src/RendererImplementation.cpp",
	"src/DeferredRendererImplementation.cpp",
	"src/ImmediateRendererImplementation.cpp",
	"src/ShaderStateComponent.cpp",
	"src/SceneViewer.cpp",
	"src/ShaderLoader.cpp",
	"src/TextureLoader.cpp",
	"src/FrameBuffer.cpp",
	"src/DepthTexture.cpp",
	"src/ColorTexture.cpp",
	"src/OrthographicCamera.cpp",
	"src/PerspectiveCamera.cpp",
	"src/Display.cpp",
	"src/TextureUnits.cpp",
	"src/CameraController.cpp",
	"src/Lights.cpp",
	"src/UniformFunctions.cpp",
]

pythonModuleSources = [
	"src/bindings/IECoreGLBinding.cpp",
	"src/bindings/RendererBinding.cpp",
	"src/bindings/BindableBinding.cpp",
	"src/bindings/ShaderBinding.cpp",
	"src/bindings/TextureBinding.cpp",
	"src/bindings/WindowBinding.cpp",
	"src/bindings/StateBinding.cpp",
	"src/bindings/RenderableBinding.cpp",
	"src/bindings/SceneBinding.cpp",
	"src/bindings/SceneViewerBinding.cpp",
	"src/bindings/ShaderLoaderBinding.cpp",
	"src/bindings/TextureLoaderBinding.cpp",
	"src/bindings/GroupBinding.cpp",
	"src/bindings/FrameBufferBinding.cpp",
	"src/bindings/ColorTextureBinding.cpp",
	"src/bindings/DepthTextureBinding.cpp",
	"src/bindings/CameraBinding.cpp",
	"src/bindings/PerspectiveCameraBinding.cpp",
	"src/bindings/OrthographicCameraBinding.cpp",
	"src/bindings/CameraControllerBinding.cpp",
]

pythonModulePythonSources = [
	"python/IECoreGL/__init__.py",
]

lib = IEBuild.SharedLibrary( ARGUMENTS, "IECoreGL", version, libSources, ["include"] )
lib.addVersionedInclude( "boost", boostVersion )
lib.addVersionedInclude( "glew", glewVersion )
lib.addVersionedDependency( "IECore", coreMajorVersion )
lib.addVersionedInclude( "OpenEXR", openEXRVersion )
lib.addDefine( "IE_CORE_MAJOR_VERSION", coreMajorVersion )
lib.addLibPath( "/usr/X11R6/lib" )
lib.addLib( "GL" )
lib.addLib( "GLU" )
lib.addLib( "glut" )
lib.addLib( "GLEW" )
lib.finalize()

pythonModule = IEBuild.PythonModule( ARGUMENTS, "IECoreGL", version, pythonModuleSources, ["include"], pythonModulePythonSources, "python/IECoreGL" )
pythonModule.setPythonVersion( pythonVersion )
pythonModule.getLibrary().setCompiler( lib.getCompiler(), lib.getCompilerVersion() )
pythonModule.getLibrary().addVersionedDependency( "IECore", coreMajorVersion )
pythonModule.getLibrary().addVersionedInclude( "OpenEXR", openEXRVersion )
pythonModule.getLibrary().addVersionedInclude( "boost", boostVersion )
pythonModule.getLibrary().addVersionedInclude( "glew", glewVersion )
pythonModule.getLibrary().addLibPath( "." )
pythonModule.getLibrary().addLib( "IECoreGL-" + version )
pythonModule.getLibrary().addLib( "boost_python" )
pythonEnv = pythonModule.finalize()

pythonEnv.Depends( pythonModule.getTargets(), lib.getTargets() )

pythonTestEnv = Environment( ENV=os.environ )
pythonTestEnv["ENV"]["PYTHONPATH"] = "python:" + pythonTestEnv["ENV"]["PYTHONPATH"]
pythonTestEnv["ENV"]["IEENV_LIBRARY_PREFIX_PATH"] = "./:"+pythonTestEnv["ENV"]["IEENV_LIBRARY_PREFIX_PATH"]
pythonTestEnv["ENV"]["COMPILER"] = pythonModule.getLibrary().getCompiler()
pythonTestEnv["ENV"]["COMPILER_VERSION"] = pythonModule.getLibrary().getCompilerVersion()

pythonTestRun = pythonTestEnv.Command( "test/pythonTest.out", "",  "python"+pythonVersion+" "+ARGUMENTS.get("TESTSCRIPT", "test/All.py") + " -v")
pythonTestEnv.Depends( pythonTestRun, pythonModule.getTargets() )

Default( pythonModule.getTargets() )
