Cortex: IECoreGL::Shader Class Reference
IECoreGL::Shader Class Reference
A class to represent GLSL shaders.
#include <Shader.h>
Public Member Functions
IE_CORE_DECLARERUNTIMETYPEDEXTENSION (IECoreGL::Shader, ShaderTypeId, Bindable)
Shader (const std::string &vertexSource, const std::string &fragmentSource)
bool operator== (const Shader &other) const
virtual void bind () const
void uniformParameterNames (std::vector< std::string > &names) const
GLint uniformParameterIndex (const std::string &parameterName) const
bool hasUniformParameter (const std::string &parameterName) const
Returns true if the Shader has a uniform parameter of the given name.
IECore::TypeId uniformParameterType (GLint parameterIndex) const
IECore::TypeId uniformParameterType (const std::string &parameterName) const
As above but by specifying the parameter by name.
void vertexParameterNames (std::vector< std::string > &names) const
Fills the passed vector with the names of all vertex shader parameters.
GLint vertexParameterIndex (const std::string &parameterName) const
bool hasVertexParameter (const std::string &parameterName) const
Returns true if the Shader has a vertex parameter of the given name.
bool vertexValueValid (GLint parameterIndex, const IECore::Data *value) const
bool vertexValueValid (const std::string &parameterName, const IECore::Data *value) const
As above, but specifying the vertex parameter by name.
void setVertexParameter (GLint parameterIndex, const IECore::Data *value, bool normalize=false)
void setVertexParameter (const std::string &parameterName, const IECore::Data *value, bool normalize=false)
As above, but specifying the vertex parameter by name.
void unsetVertexParameters ()
Unsets all vertex parameters from the shader.
getUniformParameterDefault
Returns a new data object containing the suggested default value (zero) to be set on the given parameter. The default values are not supported by OpenGL. So the shader does not have to be bound at the time of calling.
IECore::DataPtr getUniformParameterDefault (GLint parameterIndex) const
IECore::DataPtr getUniformParameterDefault (const std::string &parameterName) const
Uniform Parameter getting
These calls return the current values of shader uniform parameters. Unlike the calls to set values (see below) the shader does not have to be bound at the time of calling.
IECore::DataPtr getUniformParameter (GLint parameterIndex) const
IECore::DataPtr getUniformParameter (const std::string &parameterName) const
Uniform Parameter setting
These calls set shader parameters. They can only be called while the Shader is bound (using bind()) as the current shader - Exceptions will result if this is not the case.
bool uniformValueValid (GLint parameterIndex, IECore::TypeId type) const
bool uniformValueValid (GLint parameterIndex, const IECore::Data *value) const
bool uniformValueValid (const std::string &parameterName, const IECore::Data *value) const
As above, but specifying the uniform parameter by name.
void setUniformParameter (GLint parameterIndex, const IECore::Data *value)
template<typename T >
boost::disable_if_c
< boost::is_convertible< T,
IECore::Data * >::value >
::type setUniformParameter (GLint parameterIndex, const T &value)
void setUniformParameter (const std::string &parameterName, const IECore::Data *value)
void setUniformParameter (GLint parameterIndex, unsigned int textureUnit)
Sets the specified sampler parameter to use the texture unit indicated.
void setUniformParameter (const std::string &parameterName, unsigned int textureUnit)
void setUniformParameter (GLint parameterIndex, int value)
void setUniformParameter (const std::string &parameterName, int value)
bool uniformVectorValueValid (GLint parameterIndex, const IECore::Data *value) const
bool uniformVectorValueValid (const std::string &parameterName, const IECore::Data *value) const
As above, but specifying the uniform parameter by name.
void setUniformParameterFromVector (GLint parameterIndex, const IECore::Data *vector, unsigned int item)
void setUniformParameterFromVector (const std::string &parameterName, const IECore::Data *vector, unsigned int item)
VertexToUniform uniformParameterFromVectorSetup (GLint parameterIndex, const IECore::Data *vector) const
Returns a callable object that sets a uniform shader parameter with a single item value from a given vector.
Static Public Member Functions
Built in shaders
These functions provide access to static instances of various simple but useful shaders.
static ShaderPtr constant ()
static ShaderPtr facingRatio ()
Returns a shader which shades as a facing ratio.
Detailed Description
A class to represent GLSL shaders.
Constructor & Destructor Documentation
IECoreGL::Shader::Shader (const std::string & vertexSource, const std::string & fragmentSource)
Either vertexSource or fragmentSource may be empty to use the fixed functionality for that shader component. Throws an Exception if the shader fails to compile, or if the OpenGL version isn't sufficient to support shaders.
Member Function Documentation
virtual void IECoreGL::Shader::bind () const [virtual]
Binds the object into the current OpenGL state in whatever way is relevant to that object (install a shader, make a texture current, enable/disable something etc.).
Implements IECoreGL::Bindable.
static ShaderPtr IECoreGL::Shader::constant () [static]
Returns a shader which shades as a constant flat color using the current gl color.
void IECoreGL::Shader::setUniformParameter (const std::string & parameterName, unsigned int textureUnit)
Sets the specified sampler parameter to use the texture unit indicated. This call may be slower than the overload based on parameter indexes.
void IECoreGL::Shader::setUniformParameter (const std::string & parameterName, const IECore::Data * value)
Sets the specified parameter to the value specified. value must be of an appropriate type for the parameter - an Exception is thrown if this is not the case. This call may be slower than the overload based on parameter indexes.
template<typename T > boost::disable_if_c< boost::is_convertible< T, IECore::Data * >::value >::type IECoreGL::Shader::setUniformParameter (GLint parameterIndex, const T & value) [inline]
Sets the specified parameter to the value provided. value must be of an appropriate simple type or a Imath type.
References setUniformParameter(), IECore::RunTimeTyped::staticTypeId(), and uniformValueValid().
void IECoreGL::Shader::setUniformParameter (GLint parameterIndex, const IECore::Data * value)
Sets the specified uniform parameter to the value specified. value must be of an appropriate type for the parameter - an Exception is thrown if this is not the case.
Referenced by setUniformParameter().
void IECoreGL::Shader::setUniformParameterFromVector (GLint parameterIndex, const IECore::Data * vector, unsigned int item)
Sets the specified uniform parameter to a single item from a vector Data type. Raises an exception if the type is not compatible.
void IECoreGL::Shader::setVertexParameter (GLint parameterIndex, const IECore::Data * value, bool normalize = false)
Sets the specified vertex parameter to the value specified. value must be of an appropriate type for the parameter - an Exception is thrown if this is not the case. Derived classes can set normalize to true when they know a integer typed vector should be normalized to [-1,1] or [0,1] when passed to the shader.
GLint IECoreGL::Shader::uniformParameterIndex (const std::string & parameterName) const
Returns a numeric index for the named uniform parameter. This can be used in the calls below to avoid more expensive lookups by name. Throws an Exception if parameter does not exist.
void IECoreGL::Shader::uniformParameterNames (std::vector< std::string > & names) const
Uniform Parameters Fills the passed vector with the names of all uniform shader parameters. Structures will use the struct.component convention used in GLSL. Arrays will be returned as a single name, rather than the list array[0], array[n] names used internally in OpenGL.
IECore::TypeId IECoreGL::Shader::uniformParameterType (GLint parameterIndex) const
Returns the type of a named uniform parameter, described in terms of the most closely related IECore datatype. The type here is the type of data returned by the getUniformParameter() function below, except in the case of 2d samplers, where TextureTypeId will be returned.
bool IECoreGL::Shader::uniformValueValid (GLint parameterIndex, const IECore::Data * value) const
Returns true if the specified value is valid for setting the specified uniform parameter, and false if not.
bool IECoreGL::Shader::uniformValueValid (GLint parameterIndex, IECore::TypeId type) const
Returns true if the specified data type is valid for setting the specified uniform parameter, and false if not.
Referenced by setUniformParameter().
bool IECoreGL::Shader::uniformVectorValueValid (GLint parameterIndex, const IECore::Data * value) const
Returns true if the specified vector data is valid for setting one of it's items to the specified uniform parameter, and false if not.
GLint IECoreGL::Shader::vertexParameterIndex (const std::string & parameterName) const
Returns a numeric index for the named vertex parameter. This can be used in the calls below to avoid more expensive lookups by name. Throws an Exception if parameter does not exist.
void IECoreGL::Shader::vertexParameterNames (std::vector< std::string > & names) const
Fills the passed vector with the names of all vertex shader parameters.
Vertex Parameters
bool IECoreGL::Shader::vertexValueValid (GLint parameterIndex, const IECore::Data * value) const
Returns true if the specified vertex data object is valid for setting the specified vertex parameter, and false if not.
The documentation for this class was generated from the following file:
include/IECoreGL/Shader.h