Cortex: mel/IECoreMaya/ieParameterisedHolder.mel File Reference
mel/IECoreMaya/ieParameterisedHolder.mel File Reference
Functions
global proc string ieParameterisedHolderClassName (string $nodeName)
global proc int ieParameterisedHolderClassVersion (string $nodeName)
global proc string ieParameterisedHolderClassSearchPathEnvVar (string $nodeName)
global proc string ieParameterisedHolderClassDescription (string $nodeName)
Returns the description for the class being held.
global proc int[] ieParameterisedHolderClassVersions (string $nodeName)
global proc ieParameterisedHolderSetParameterised (string $nodeName, string $className, int $classVersion, string $searchPathEnvVar)
Detailed Description
This file defines functions which can be used with any of the node types instantiated from the template ParameterisedHolder class.
Function Documentation
global proc string ieParameterisedHolderClassName (string $ nodeName)
Returns the name of the class being held.
Todo:
Handle case where getParameterised() returns None
Referenced by ieParameterisedHolderClassVersions().
global proc string ieParameterisedHolderClassSearchPathEnvVar (string $ nodeName)
Returns the name of the environment variable which specifies the searchpaths this node looks for classes on.
Todo:
Handle case where getParameterised() returns None
Referenced by ieParameterisedHolderClassVersions().
global proc int ieParameterisedHolderClassVersion (string $ nodeName)
Returns the version of the class being held.
Todo:
Handle case where getParameterised() returns None
global proc int [] ieParameterisedHolderClassVersions (string $ nodeName)
Returns an int array containing all the valid versions of the class currently being held by $nodeName.
References ieParameterisedHolderClassName(), and ieParameterisedHolderClassSearchPathEnvVar().
global proc ieParameterisedHolderSetParameterised (string $ nodeName, string $ className, int $ classVersion, string $ searchPathEnvVar)
Sets the parameterised class being held by this node. If $classVersion is less than 0 then the default version for that class will be loaded.
Referenced by ieProceduralHolderCreate().