Cortex: IECore Namespace Reference
IECore Namespace Reference
This namespace contains all components of the core library.
Classes
class AddSmoothSkinningInfluencesOp
class AttributeBlock
A context object intended for use with python's "with" syntax.
class AttributeCache
class AttributeState
class BGEOParticleReader
class BinaryFrameList
class BINMeshReader
class BINParticleWriter
class BlindDataHolder
A class which represents an object with some blind data attached.
class BlobbyImplicitSurfaceFunction
class BoundedKDTree
struct BoxTypeTraits
struct BoxTraits
class CachedImplicitSurfaceFunction
class CachedReader
class CameraController
class CapturingRenderer
class ChannelOp
class CineonToLinearDataConversion
A class to perform data conversion from Cineon log values to linear.
class CineonToLinearOp
class CINImageReader
class CINImageWriter
class CircularIterator
class ClassData
class ClientDisplayDriver
class ColorSpaceTransformOp
struct ColorTransform
Base class for data conversions.
class ColorTransformOp
class CompoundData
class CompoundDataConversion
class CompoundFrameList
class CompoundMessageHandler
class CompoundObject
class CompoundParameter
class CompressSmoothSkinningDataOp
class ContrastSmoothSkinningWeightsOp
class Converter
class CSGImplicitSurfaceFunction
class CubeColorLookup
The CubeColorLookup, templated on either float or double, performs interpolated lookups into color tables.
class CubicBasis
class CurveExtrudeOp
class CurveLineariser
class CurvesMergeOp
class CurvesPrimitive
class CurvesPrimitiveEvaluator
class CurveTangentsOp
class CurveTracer
class Data
class DataCastOp
struct DataConversion
Base class for data conversions.
struct DataConvert
class DataConvertOp
class DataInterleaveOp
class DataPromoteOp
class DecompressSmoothSkinningDataOp
class DeepImageConverter
class DeepImageReader
class DeepImageWriter
class DeepPixel
struct Deleter
A simple unary functor which calls delete on its argument, and resets it to zero.
struct ArrayDeleter
A simple unary functor which calls delete[] on its argument, and resets it to zero.
struct NullDeleter
struct DimensionTraits
class DirNameParameter
class Display
class DisplayDriver
class DisplayDriverServer
class DPXImageReader
class DPXImageWriter
class EmptyFrameList
class EnvMapSampler
class EnvMapSHProjector
class EuclideanToSphericalTransform
class Exception
class IOException
Base class for Input/Output exceptions.
class FileNotFoundIOException
A class to represent "file not found" exceptions.
class InvalidArgumentException
Base class for Invalid Argument exceptions.
class PermissionDeniedIOException
A class to represent "permission denied" exceptions.
class NotImplementedException
A class to represent "not implemented" exceptions.
class ExclusionFrameList
class EXRImageReader
class EXRImageWriter
class FaceAreaOp
class FaceVaryingPromotionOp
class FileIndexedIO
class FileNameParameter
class FileSequence
class FileSequenceParameter
class FileSequenceVectorParameter
class FileSystemIndexedIO
class FilteredMessageHandler
class Font
class FrameList
class FrameRange
class FromCoreConverter
class Grade
class Group
class HdrMergeOp
class HeaderGenerator
class HierarchicalCache
class HitMissTransform
class IFFFile
class IFFHairReader
class ImageCompositeOp
class ImageCropOp
class ImageDiffOp
class ImageDisplayDriver
class ImagePremultiplyOp
class ImagePrimitive
class ImagePrimitiveEvaluator
class ImageReader
class ImageThinner
class ImageUnpremultiplyOp
class ImageWriter
class ImathRandAdapter
class ImplicitSurfaceFunction
class IndexedIOFilter
class IndexedIONullFilter
A Null filter. Performs no filtering.
class IndexedIOEntryTypeFilter
A class to filter out Entries which don't have the specified type.
class IndexedIORegexFilter
A class to filter out Entries whose names don't match the specified regular expression.
class IndexedIOInterface
class IndexedIOPath
class Interned
class InterpolatedCache
class IntrusivePtr
class InverseDistanceWeightedInterpolation
class JPEGImageReader
class JPEGImageWriter
class KDTree
class LevelFilteredMessageHandler
class LevenbergMarquardt
class Light
class LimitSmoothSkinningInfluencesOp
class LinearToCineonDataConversion
A class to perform data conversion from linear to Cineon log values.
class LinearToCineonOp
struct LinearToPanalogDataConversion
A class to perform data conversion from linear values to Panalog.
class LinearToPanalogOp
struct LinearToRec709DataConversion
A class to perform data conversion from linear values to Rec709.
class LinearToRec709Op
struct LinearToSRGBDataConversion
A class to perform data conversion from linear values to sRGB.
class LinearToSRGBOp
class LineSegment
class Lookup
class LRUCache
class LuminanceOp
class MappedRandomPointDistributionOp
class MarchingCubes
class MarschnerBCSDF
class MarschnerLookupTableOp
class MarschnerParameter
class MatrixMultiplyOp
struct MatConvert
struct MatrixTraits
struct MatrixTraits< Imath::M33f >
Specialisations for Imath types.
struct MeanSquaredError
class MedianCutSampler
class MemoryStream
A boost.iostreams "device" for reading to/writing from memory.
class MeshDistortionsOp
class MeshMergeOp
class MeshNormalsOp
class MeshPrimitive
class MeshPrimitiveBuilder
class MeshPrimitiveEvaluator
class MeshPrimitiveImplicitSurfaceFunction
class MeshPrimitiveImplicitSurfaceOp
class MeshPrimitiveShrinkWrapOp
class MeshTangentsOp
class MeshVertexReorderOp
class MessageHandler
class MixSmoothSkinningWeightsOp
class ModifyOp
class MotionBlock
A context object intended for use with python's "with" syntax.
class MotionPrimitive
class MurmurHash
class NormalizeSmoothSkinningWeightsOp
class NParticleReader
class NullMessageHandler
class NullObject
class NumericParameter
class NURBSPrimitive
class Object
class ObjectParameter
class ObjectReader
class ObjectVector
An Object which holds a vector of child Objects.
class ObjectWriter
class OBJReader
class Op
class OStreamMessageHandler
class OversamplesCalculator
class PanalogToLinearDataConversion
A class to perform data conversion from Panalog values to linear.
class PanalogToLinearOp
class Parameter
class Parameterised
class ParameterisedInterface
class ParameterisedProcedural
class ParticleMeshOp
class ParticleReader
class ParticleWriter
class PatchMeshPrimitive
class PathParameter
class PathVectorParameter
class PDCParticleReader
class PDCParticleWriter
struct SmoothStepFalloff
struct SmootherStepFalloff
class PerlinNoise
class PlaneImplicitSurfaceFunction
class PNGImageReader
class PointBoundsOp
class PointDensitiesOp
class PointDistribution
class PointDistributionOp
class PointMeshOp
class PointNormalsOp
class PointRepulsionOp
class PointSmoothSkinningOp
class PointsMotionOp
class PointsPrimitive
class PointsPrimitiveEvaluator
class PointVelocityDisplaceOp
class PolygonIterator
class PolygonVertexIterator
class PreWorldRenderable
class Primitive
class PrimitiveEvaluator
class PrimitiveImplicitSurfaceFunction
class PrimitiveOp
struct PrimitiveVariable
class RadixSort
class RandomRotationOp
class Reader
class RealSphericalHarmonicFunction
struct Rec709ToLinearDataConversion
A class to perform data conversion from Rec709 values to linear.
class Rec709ToLinearOp
class RefCounted
class RemoveSmoothSkinningInfluencesOp
class Renderable
class Renderer
class ReorderedFrameList
class ReorderSmoothSkinningInfluencesOp
class ReversedFrameList
class RGBToXYZColorTransform
A templated ColorTransform class to perform RGB->XYZ color transformations.
class RunTimeTyped
struct ScaledDataConversion
class ScopedMessageHandler
class SearchPath
class SGIImageReader
class Shader
class SimpleSubsurface
class LongDataAlias
class SmoothSkinningData
class SmoothSmoothSkinningWeightsOp
struct SpaceTransform
Base class for data conversions.
class SphereImplicitSurfaceFunction
class SpherePrimitive
class SpherePrimitiveEvaluator
class SphericalHarmonics
class SphericalHarmonicsProjector
class SphericalHarmonicsRotationMatrix
class SphericalHarmonicsTensor
class SphericalHarmonicsTransferMatrix
class SphericalToEuclideanTransform
class Spline
class SplineToImage
struct SRGBToLinearDataConversion
A class to perform data conversion from sRGB values to linear.
class SRGBToLinearOp
class StateRenderable
class SummedAreaOp
class TGAImageReader
class TGAImageWriter
class TIFFImageReader
class TIFFImageWriter
class TimePeriod
A default constructable boost::posix_time::time_period, for use as parameter to IECore::TypedData template.
class Timer
class ToCoreConverter
class Transform
class TransformationMatrix
class TransformBlock
A context object intended for use with python's "with" syntax.
class TransformOp
class TriangulateOp
class Triangulator
class Turbulence
class TypedData
class TypedDataTraits
class TypedObjectParameter
class TypedParameter
A template class for simple typed parameters. TypedData<T> is used to store the value.
class TypedPrimitiveOp
The TypedPrimitiveOp template defines a base class for Ops which modify primitives of a specific type.
struct TypeInfoCmp
class UniformRandomPointDistributionOp
class UVDistortOp
Distorts an ImagePrimitive by using a UV map as reference.
class ValidatedStringParameter
class VectorDataFilterOp
struct VecConvert
struct VectorTraits
struct VectorTraits< int >
Specialisation for int type to allow its use as a 1d vector.
struct VectorTraits< float >
Specialisation for float type to allow its use as a 1d vector.
struct VectorTraits< double >
Specialisation for double type to allow its use as a 1d vector.
class LongVectorDataAlias
class VisibleRenderable
class WarpOp
class WorldBlock
A context object intended for use with python's "with" syntax.
class Writer
class XYYToXYZColorTransform
A templated ColorTransform class to perform xyY->XYZ color transformations.
class XYZToRGBColorTransform
A templated ColorTransform class to perform XYZ->RGB color transformations.
class XYZToXYYColorTransform
A templated ColorTransform class to perform XYZ->xyY color transformations.
class YUVImageWriter
class ZhuBridsonImplicitSurfaceFunction
class Formatter
The Formatter class defines an interface for specifying simple structured output without having to be concerned with exactly how that output is displayed.
class WrappedTextFormatter
Implements the Formatter interface in a very simple form, just outputting text with word wrapping to a file object.
class ClassLoader
This class defines methods for creating instances of classes defined in python modules on disk.
class OptionalCompoundParameter
This class implements a CompoundParameter that do not validate optional parameters if they are undefined.
class FileExaminer
The FileExaminer class is an abstract base class for classes which can perform some query on a file.
class NukeFileExaminer
The NukeFileExaminer class implements the FileExaminer interface for nuke script files.
class RIBFileExaminer
The RIBFileExaminer class implements the FileExaminer interface for RIB files.
class Struct
The Struct class provides an incredibly simple container with attribute access defined.
class MenuItemDefinition
The MenuItemDefinition class defines the contents of a menu item for use with the MenuDefinition class.
class MenuDefinition
The MenuDefinition class defines the contents of a hierarchical menu containing MenuItemDefinition instances.
class ParameterParser
This class defines a means of parsing a list of string arguments with respect to a Parameter definition.
class CapturingMessageHandler
The CapturingMessageHandler simply stores all messages passed to it in an attribute called messages.
class LayeredDict
This class takes a stack of dictionary like objects and provides read only access to them as if they were one, falling through to lower dictionaries if the requested item isn't in the ones above.
class CompoundVectorParameter
This class is a CompoundParameter that only accepts vector parameters with the same length.
class SubstitutedDict
Acts like a dictionary, but performs substitutions on any string or StringData values retrieved from it.
class VisualiserProcedural
An incredibly simple procedural which just renders an object passed to it via a Parameter.
class ClassParameter
The ClassParameter is a specialised CompoundParameter which allows its children to be specified by another Parameterised class which is loaded using the ClassLoader.
class ClassVectorParameter
The ClassVectorParameter is similar to the ClassParameter but instead of holding a single class it holds many classes, each storing its parameters under a named child of the ClassVectorParameter.
class CompoundStream
A class which acts like a python file object but outputs to several underlying files.
class IgnoredExceptions
A context object intended for use with python's "with" syntax.
class Preset
The Preset class serves as a base class for the implementation of 'presets'.
class BasicPreset
Implements a Preset to permit values to be saved and restored from a Parameterised object.
class RelativePreset
Implements a Preset that represents changes between two Parameter objects.
Typedefs
typedef
BlobbyImplicitSurfaceFunction
< Imath::V3f, float > BlobbyImplicitSurfaceFunctionV3ff
typedef
BlobbyImplicitSurfaceFunction
< Imath::V3f, double > BlobbyImplicitSurfaceFunctionV3fd
typedef
BlobbyImplicitSurfaceFunction
< Imath::V3d, float > BlobbyImplicitSurfaceFunctionV3df
typedef
BlobbyImplicitSurfaceFunction
< Imath::V3d, double > BlobbyImplicitSurfaceFunctionV3dd
typedef BoundedKDTree
< std::vector< Imath::Box2f >
::const_iterator > Box2fTree
typedef BoundedKDTree
< std::vector< Imath::Box2d >
::const_iterator > Box2dTree
typedef BoundedKDTree
< std::vector< Imath::Box3f >
::const_iterator > Box3fTree
typedef BoundedKDTree
< std::vector< Imath::Box3d >
::const_iterator > Box3dTree
typedef
CachedImplicitSurfaceFunction
< Imath::V3f, float > CachedImplicitSurfaceFunctionV3ff
typedef
CachedImplicitSurfaceFunction
< Imath::V3f, double > CachedImplicitSurfaceFunctionV3fd
typedef
CachedImplicitSurfaceFunction
< Imath::V3d, float > CachedImplicitSurfaceFunctionV3df
typedef
CachedImplicitSurfaceFunction
< Imath::V3d, double > CachedImplicitSurfaceFunctionV3dd
typedef std::map
< InternedString, DataPtr > CompoundDataMap
The type of Data held by the CompoundData typedef.
typedef TypedData
< CompoundDataMap > CompoundDataBase
typedef
CSGImplicitSurfaceFunction
< Imath::V3f, float > CSGImplicitSurfaceFunctionV3ff
typedef
CSGImplicitSurfaceFunction
< Imath::V3f, double > CSGImplicitSurfaceFunctionV3fd
typedef
CSGImplicitSurfaceFunction
< Imath::V3d, float > CSGImplicitSurfaceFunctionV3df
typedef
CSGImplicitSurfaceFunction
< Imath::V3d, double > CSGImplicitSurfaceFunctionV3dd
typedef CubeColorLookup< float > CubeColorLookupf
typedef CubeColorLookup< double > CubeColorLookupd
typedef TypedData
< CubeColorLookupf > CubeColorLookupfData
typedef TypedData
< CubeColorLookupd > CubeColorLookupdData
typedef TypedParameter
< CubeColorLookupf > CubeColorLookupfParameter
typedef TypedParameter
< CubeColorLookupd > CubeColorLookupdParameter
typedef CubicBasis< float > CubicBasisf
typedef CubicBasis< double > CubicBasisd
typedef TypedData
< boost::posix_time::ptime > DateTimeData
typedef TypedParameter
< boost::posix_time::ptime > DateTimeParameter
typedef
EuclideanToSphericalTransform
< Imath::V3f, Imath::V2f > EuclideanToSphericalTransform3f2f
typedef
EuclideanToSphericalTransform
< Imath::V3f, Imath::V3f > EuclideanToSphericalTransform3f3f
typedef
EuclideanToSphericalTransform
< Imath::V3d, Imath::V2d > EuclideanToSphericalTransform3d2d
typedef
EuclideanToSphericalTransform
< Imath::V3d, Imath::V3d > EuclideanToSphericalTransform3d3d
typedef ImathRandAdapter
< Imath::Rand32 > ImathRand32Adapter
typedef ImathRandAdapter
< Imath::Rand48 > ImathRand48Adapter
typedef
ImplicitSurfaceFunction
< Imath::V3f, float > ImplicitSurfaceFunctionV3ff
typedef
ImplicitSurfaceFunction
< Imath::V3f, double > ImplicitSurfaceFunctionV3fd
typedef
ImplicitSurfaceFunction
< Imath::V3d, float > ImplicitSurfaceFunctionV3df
typedef
ImplicitSurfaceFunction
< Imath::V3d, double > ImplicitSurfaceFunctionV3dd
typedef Interned< std::string > InternedString
typedef
InverseDistanceWeightedInterpolation
< std::vector< Imath::V2f >
::const_iterator, std::vector
< float >::const_iterator > InverseDistanceWeightedInterpolationV2ff
typedef
InverseDistanceWeightedInterpolation
< std::vector< Imath::V2d >
::const_iterator, std::vector
< double >::const_iterator > InverseDistanceWeightedInterpolationV2dd
typedef
InverseDistanceWeightedInterpolation
< std::vector< Imath::V3f >
::const_iterator, std::vector
< float >::const_iterator > InverseDistanceWeightedInterpolationV3ff
typedef
InverseDistanceWeightedInterpolation
< std::vector< Imath::V3d >
::const_iterator, std::vector
< double >::const_iterator > InverseDistanceWeightedInterpolationV3dd
typedef
InverseDistanceWeightedInterpolation
< std::vector< Imath::V2f >
::const_iterator, std::vector
< Imath::V2f >::const_iterator > InverseDistanceWeightedInterpolationV2fV2f
typedef
InverseDistanceWeightedInterpolation
< std::vector< Imath::V2d >
::const_iterator, std::vector
< Imath::V2d >::const_iterator > InverseDistanceWeightedInterpolationV2dV2d
typedef
InverseDistanceWeightedInterpolation
< std::vector< Imath::V3f >
::const_iterator, std::vector
< Imath::V3f >::const_iterator > InverseDistanceWeightedInterpolationV3fV3f
typedef
InverseDistanceWeightedInterpolation
< std::vector< Imath::V3d >
::const_iterator, std::vector
< Imath::V3d >::const_iterator > InverseDistanceWeightedInterpolationV3dV3d
typedef KDTree< std::vector
< Imath::V2f >::const_iterator > V2fTree
typedef KDTree< std::vector
< Imath::V2d >::const_iterator > V2dTree
typedef KDTree< std::vector
< Imath::V3f >::const_iterator > V3fTree
typedef KDTree< std::vector
< Imath::V3d >::const_iterator > V3dTree
typedef LineSegment< Imath::V3f > LineSegment3f
typedef LineSegment< Imath::V3d > LineSegment3d
typedef LineSegment< Imath::V2f > LineSegment2f
typedef LineSegment< Imath::V2d > LineSegment2d
typedef Lookup< float, float > Lookupff
typedef Lookup< double, double > Lookupdd
typedef Lookup< float,
Imath::Color3f > LookupfColor3f
typedef Lookup< float,
Imath::Color4f > LookupfColor4f
typedef MarschnerBCSDF
< Imath::Color3f > MarschnerBCSDFC3f
Typedefs for common uses.
typedef MessageHandler Msg = MessageHandler
typedef for brevity.
typedef NumericParameter< int > IntParameter
typedef NumericParameter< float > FloatParameter
typedef NumericParameter< double > DoubleParameter
typedef PerlinNoise
< Imath::V3f, float,
SmootherStepFalloff< float > > PerlinNoiseV3ff
Typedefs for common uses.
typedef PerlinNoise
< Imath::V2f, float,
SmootherStepFalloff< float > > PerlinNoiseV2ff
typedef PerlinNoise< float,
float, SmootherStepFalloff
< float > > PerlinNoiseff
typedef PerlinNoise
< Imath::V3f, Imath::V2f,
SmootherStepFalloff< float > > PerlinNoiseV3fV2f
typedef PerlinNoise
< Imath::V2f, Imath::V2f,
SmootherStepFalloff< float > > PerlinNoiseV2fV2f
typedef PerlinNoise< float,
Imath::V2f,
SmootherStepFalloff< float > > PerlinNoisefV2f
typedef PerlinNoise
< Imath::V3f, Imath::V3f,
SmootherStepFalloff< float > > PerlinNoiseV3fV3f
typedef PerlinNoise
< Imath::V2f, Imath::V3f,
SmootherStepFalloff< float > > PerlinNoiseV2fV3f
typedef PerlinNoise< float,
Imath::V3f,
SmootherStepFalloff< float > > PerlinNoisefV3f
typedef PerlinNoise
< Imath::V3f, Imath::Color3f,
SmootherStepFalloff< float > > PerlinNoiseV3fColor3f
typedef PerlinNoise
< Imath::V2f, Imath::Color3f,
SmootherStepFalloff< float > > PerlinNoiseV2fColor3f
typedef PerlinNoise< float,
Imath::Color3f,
SmootherStepFalloff< float > > PerlinNoisefColor3f
typedef
PlaneImplicitSurfaceFunction
< Imath::V3f, float > PlaneImplicitSurfaceFunctionV3ff
typedef
PlaneImplicitSurfaceFunction
< Imath::V3f, double > PlaneImplicitSurfaceFunctionV3fd
typedef
PlaneImplicitSurfaceFunction
< Imath::V3d, float > PlaneImplicitSurfaceFunctionV3df
typedef
PlaneImplicitSurfaceFunction
< Imath::V3d, double > PlaneImplicitSurfaceFunctionV3dd
typedef std::map< std::string,
PrimitiveVariable > PrimitiveVariableMap
A simple type to hold named PrimitiveVariables.
typedef TypedData< bool > BoolData
typedef TypedData< float > FloatData
typedef TypedData< double > DoubleData
typedef TypedData< int > IntData
typedef TypedData< unsigned int > UIntData
typedef TypedData< char > CharData
typedef TypedData< unsigned char > UCharData
typedef TypedData< short > ShortData
typedef TypedData< unsigned short > UShortData
typedef TypedData< int64_t > Int64Data
typedef TypedData< uint64_t > UInt64Data
typedef TypedData< std::string > StringData
typedef TypedData< half > HalfData
typedef TypedData< Imath::V2i > V2iData
typedef TypedData< Imath::V3i > V3iData
typedef TypedData< Imath::V2f > V2fData
typedef TypedData< Imath::V3f > V3fData
typedef TypedData< Imath::V2d > V2dData
typedef TypedData< Imath::V3d > V3dData
typedef TypedData< Imath::Color3f > Color3fData
typedef TypedData< Imath::Color4f > Color4fData
typedef TypedData
< Imath::Color3< double > > Color3dData
typedef TypedData
< Imath::Color4< double > > Color4dData
typedef TypedData< Imath::Box2i > Box2iData
typedef TypedData< Imath::Box3i > Box3iData
typedef TypedData< Imath::Box2f > Box2fData
typedef TypedData< Imath::Box3f > Box3fData
typedef TypedData< Imath::Box2d > Box2dData
typedef TypedData< Imath::Box3d > Box3dData
typedef TypedData< Imath::M33f > M33fData
typedef TypedData< Imath::M33d > M33dData
typedef TypedData< Imath::M44f > M44fData
typedef TypedData< Imath::M44d > M44dData
typedef TypedData< Imath::Quatf > QuatfData
typedef TypedData< Imath::Quatd > QuatdData
typedef TypedData< LineSegment3f > LineSegment3fData
typedef TypedData< LineSegment3d > LineSegment3dData
typedef TypedParameter< bool > BoolParameter
typedef TypedParameter
< std::string > StringParameter
typedef TypedParameter
< Imath::V2i > V2iParameter
typedef TypedParameter
< Imath::V3i > V3iParameter
typedef TypedParameter
< Imath::V2f > V2fParameter
typedef TypedParameter
< Imath::V3f > V3fParameter
typedef TypedParameter
< Imath::V2d > V2dParameter
typedef TypedParameter
< Imath::V3d > V3dParameter
typedef TypedParameter
< Imath::Color3f > Color3fParameter
typedef TypedParameter
< Imath::Color4f > Color4fParameter
typedef TypedParameter
< Imath::Box2i > Box2iParameter
typedef TypedParameter
< Imath::Box3i > Box3iParameter
typedef TypedParameter
< Imath::Box2f > Box2fParameter
typedef TypedParameter
< Imath::Box3f > Box3fParameter
typedef TypedParameter
< Imath::Box2d > Box2dParameter
typedef TypedParameter
< Imath::Box3d > Box3dParameter
typedef TypedParameter
< Imath::M44f > M44fParameter
typedef TypedParameter
< Imath::M44d > M44dParameter
typedef TypedParameter
< TransformationMatrixf > TransformationMatrixfParameter
typedef TypedParameter
< TransformationMatrixd > TransformationMatrixdParameter
typedef TypedParameter
< LineSegment3f > LineSegment3fParameter
typedef TypedParameter
< LineSegment3d > LineSegment3dParameter
typedef
SphereImplicitSurfaceFunction
< Imath::V3f, float > SphereImplicitSurfaceFunctionV3ff
typedef
SphereImplicitSurfaceFunction
< Imath::V3f, double > SphereImplicitSurfaceFunctionV3fd
typedef
SphereImplicitSurfaceFunction
< Imath::V3d, float > SphereImplicitSurfaceFunctionV3df
typedef
SphereImplicitSurfaceFunction
< Imath::V3d, double > SphereImplicitSurfaceFunctionV3dd
typedef SphericalHarmonics< float > SHf
typedef SphericalHarmonics
< double > SHd
typedef SphericalHarmonics
< Imath::V3f > SHV3f
typedef SphericalHarmonics
< Imath::V3d > SHV3d
typedef SphericalHarmonics
< Imath::Color3f > SHColor3f
typedef
SphericalHarmonicsProjector
< float > SHProjectorf
typedef
SphericalHarmonicsProjector
< double > SHProjectord
typedef
SphericalHarmonicsRotationMatrix
< float > SHRotationf
typedef
SphericalHarmonicsRotationMatrix
< double > SHRotationd
typedef
SphericalHarmonicsTransferMatrix
< double > SHTransferMatrixd
typedef
SphericalHarmonicsTransferMatrix
< float > SHTransferMatrixf
typedef
SphericalToEuclideanTransform
< Imath::V2f, Imath::V3f > SphericalToEuclideanTransform2f3f
typedef
SphericalToEuclideanTransform
< Imath::V3f, Imath::V3f > SphericalToEuclideanTransform3f3f
typedef
SphericalToEuclideanTransform
< Imath::V2d, Imath::V3d > SphericalToEuclideanTransform2d3d
typedef
SphericalToEuclideanTransform
< Imath::V3d, Imath::V3d > SphericalToEuclideanTransform3d3d
typedef Spline< float, float > Splineff
typedef Spline< double, double > Splinedd
typedef Spline< float,
Imath::Color3f > SplinefColor3f
typedef Spline< float,
Imath::Color4f > SplinefColor4f
typedef TypedData< Splineff > SplineffData
typedef TypedData< Splinedd > SplineddData
typedef TypedData< SplinefColor3f > SplinefColor3fData
typedef TypedData< SplinefColor4f > SplinefColor4fData
typedef TypedParameter< Splineff > SplineffParameter
typedef TypedParameter< Splinedd > SplineddParameter
typedef TypedParameter
< SplinefColor3f > SplinefColor3fParameter
typedef TypedParameter
< SplinefColor4f > SplinefColor4fParameter
typedef TypedData
< boost::posix_time::time_duration > TimeDurationData
typedef TypedParameter
< boost::posix_time::time_duration > TimeDurationParameter
typedef TypedData< TimePeriod > TimePeriodData
typedef TypedParameter
< TimePeriod > TimePeriodParameter
typedef TransformationMatrix
< double > TransformationMatrixd
typedef TransformationMatrix
< float > TransformationMatrixf
typedef TypedData
< TransformationMatrixf > TransformationMatrixfData
typedef TypedData
< TransformationMatrixd > TransformationMatrixdData
typedef Triangulator
< std::vector< Imath::V2f >
::const_iterator > V2fTriangulator
typedef Triangulator
< std::vector< Imath::V3f >
::const_iterator > V3fTriangulator
typedef Triangulator
< std::vector< Imath::V2d >
::const_iterator > V2dTriangulator
typedef Triangulator
< std::vector< Imath::V3d >
::const_iterator > V3dTriangulator
typedef Turbulence
< PerlinNoiseV3ff > TurbulenceV3ff
Typedefs for common uses.
typedef Turbulence
< PerlinNoiseV2ff > TurbulenceV2ff
typedef Turbulence< PerlinNoiseff > Turbulenceff
typedef Turbulence
< PerlinNoiseV3fV2f > TurbulenceV3fV2f
typedef Turbulence
< PerlinNoiseV2fV2f > TurbulenceV2fV2f
typedef Turbulence
< PerlinNoisefV2f > TurbulencefV2f
typedef Turbulence
< PerlinNoiseV3fV3f > TurbulenceV3fV3f
typedef Turbulence
< PerlinNoiseV2fV3f > TurbulenceV2fV3f
typedef Turbulence
< PerlinNoisefV3f > TurbulencefV3f
typedef Turbulence
< PerlinNoiseV3fColor3f > TurbulenceV3fColor3f
typedef Turbulence
< PerlinNoiseV2fColor3f > TurbulenceV2fColor3f
typedef Turbulence
< PerlinNoisefColor3f > TurbulencefColor3f
typedef TypedObjectParameter
< Renderable > RenderableParameter
typedef TypedObjectParameter
< StateRenderable > StateRenderableParameter
typedef TypedObjectParameter
< AttributeState > AttributeStateParameter
typedef TypedObjectParameter
< Shader > ShaderParameter
typedef TypedObjectParameter
< Transform > TransformParameter
typedef TypedObjectParameter
< MatrixMotionTransform > MatrixMotionTransformParameter
typedef TypedObjectParameter
< MatrixTransform > MatrixTransformParameter
typedef TypedObjectParameter
< VisibleRenderable > VisibleRenderableParameter
typedef TypedObjectParameter
< Group > GroupParameter
typedef TypedObjectParameter
< CompoundObject > CompoundObjectParameter
typedef TypedObjectParameter
< ObjectVector > ObjectVectorParameter
typedef TypedObjectParameter
< SmoothSkinningData > SmoothSkinningDataParameter
typedef TypedObjectParameter
< ImagePrimitive > ImagePrimitiveParameter
typedef TypedObjectParameter
< MotionPrimitive > MotionPrimitiveParameter
typedef TypedObjectParameter
< Primitive > PrimitiveParameter
typedef TypedObjectParameter
< MeshPrimitive > MeshPrimitiveParameter
typedef TypedObjectParameter
< CurvesPrimitive > CurvesPrimitiveParameter
typedef TypedObjectParameter
< PointsPrimitive > PointsPrimitiveParameter
typedef TypedData< std::vector
< bool > > BoolVectorData
typedef TypedData< std::vector
< half > > HalfVectorData
typedef TypedData< std::vector
< float > > FloatVectorData
typedef TypedData< std::vector
< double > > DoubleVectorData
typedef TypedData< std::vector
< int > > IntVectorData
typedef TypedData< std::vector
< unsigned int > > UIntVectorData
typedef TypedData< std::vector
< char > > CharVectorData
typedef TypedData< std::vector
< unsigned char > > UCharVectorData
typedef TypedData< std::vector
< short > > ShortVectorData
typedef TypedData< std::vector
< unsigned short > > UShortVectorData
typedef TypedData< std::vector
< int64_t > > Int64VectorData
typedef TypedData< std::vector
< uint64_t > > UInt64VectorData
typedef TypedData< std::vector
< std::string > > StringVectorData
typedef TypedData< std::vector
< Imath::V2f > > V2fVectorData
typedef TypedData< std::vector
< Imath::V2d > > V2dVectorData
typedef TypedData< std::vector
< Imath::V2i > > V2iVectorData
typedef TypedData< std::vector
< Imath::V3f > > V3fVectorData
typedef TypedData< std::vector
< Imath::V3d > > V3dVectorData
typedef TypedData< std::vector
< Imath::V3i > > V3iVectorData
typedef TypedData< std::vector
< Imath::Box2i > > Box2iVectorData
typedef TypedData< std::vector
< Imath::Box2f > > Box2fVectorData
typedef TypedData< std::vector
< Imath::Box2d > > Box2dVectorData
typedef TypedData< std::vector
< Imath::Box3i > > Box3iVectorData
typedef TypedData< std::vector
< Imath::Box3f > > Box3fVectorData
typedef TypedData< std::vector
< Imath::Box3d > > Box3dVectorData
typedef TypedData< std::vector
< Imath::M33f > > M33fVectorData
typedef TypedData< std::vector
< Imath::M33d > > M33dVectorData
typedef TypedData< std::vector
< Imath::M44f > > M44fVectorData
typedef TypedData< std::vector
< Imath::M44d > > M44dVectorData
typedef TypedData< std::vector
< Imath::Quatf > > QuatfVectorData
typedef TypedData< std::vector
< Imath::Quatd > > QuatdVectorData
typedef TypedData< std::vector
< Imath::Color3f > > Color3fVectorData
typedef TypedData< std::vector
< Imath::Color4f > > Color4fVectorData
typedef TypedData< std::vector
< Imath::Color3< double > > > Color3dVectorData
typedef TypedData< std::vector
< Imath::Color4< double > > > Color4dVectorData
typedef TypedParameter
< std::vector< bool > > BoolVectorParameter
typedef TypedParameter
< std::vector< int > > IntVectorParameter
typedef TypedParameter
< std::vector< float > > FloatVectorParameter
typedef TypedParameter
< std::vector< double > > DoubleVectorParameter
typedef TypedParameter
< std::vector< std::string > > StringVectorParameter
typedef TypedParameter
< std::vector< Imath::V2f > > V2fVectorParameter
typedef TypedParameter
< std::vector< Imath::V3f > > V3fVectorParameter
typedef TypedParameter
< std::vector< Imath::V2d > > V2dVectorParameter
typedef TypedParameter
< std::vector< Imath::V3d > > V3dVectorParameter
typedef TypedParameter
< std::vector< Imath::Box3f > > Box3fVectorParameter
typedef TypedParameter
< std::vector< Imath::Box3d > > Box3dVectorParameter
typedef TypedParameter
< std::vector< Imath::M33f > > M33fVectorParameter
typedef TypedParameter
< std::vector< Imath::M44f > > M44fVectorParameter
typedef TypedParameter
< std::vector< Imath::M33d > > M33dVectorParameter
typedef TypedParameter
< std::vector< Imath::M44d > > M44dVectorParameter
typedef TypedParameter
< std::vector< Imath::Quatf > > QuatfVectorParameter
typedef TypedParameter
< std::vector< Imath::Quatd > > QuatdVectorParameter
typedef TypedParameter
< std::vector< Imath::Color3f > > Color3fVectorParameter
typedef TypedParameter
< std::vector< Imath::Color4f > > Color4fVectorParameter
typedef
ZhuBridsonImplicitSurfaceFunction
< Imath::V3f, float > ZhuBridsonImplicitSurfaceFunctionV3ff
typedef
ZhuBridsonImplicitSurfaceFunction
< Imath::V3f, double > ZhuBridsonImplicitSurfaceFunctionV3fd
typedef
ZhuBridsonImplicitSurfaceFunction
< Imath::V3d, float > ZhuBridsonImplicitSurfaceFunctionV3df
typedef
ZhuBridsonImplicitSurfaceFunction
< Imath::V3d, double > ZhuBridsonImplicitSurfaceFunctionV3dd
Enumerations
enum Winding { ClockwiseWinding = 0, CounterClockwiseWinding = 1 }
enum TypeId {
InvalidTypeId = 0, ObjectTypeId = 1, DataTypeId = 2, FloatVectorDataTypeId = 3,
DoubleVectorDataTypeId = 4, IntVectorDataTypeId = 5, UIntVectorDataTypeId = 6, CharVectorDataTypeId = 7,
UCharVectorDataTypeId = 8, V2fVectorDataTypeId = 9, V2dVectorDataTypeId = 10, V3fVectorDataTypeId = 11,
V3dVectorDataTypeId = 12, Box3fVectorDataTypeId = 13, Box3dVectorDataTypeId = 14, M33fVectorDataTypeId = 15,
M33dVectorDataTypeId = 16, M44fVectorDataTypeId = 17, M44dVectorDataTypeId = 18, QuatfVectorDataTypeId = 19,
QuatdVectorDataTypeId = 20, StringVectorDataTypeId = 21, FloatDataTypeId = 22, DoubleDataTypeId = 23,
IntDataTypeId = 24, LongDataTypeId = 25, UIntDataTypeId = 26, CharDataTypeId = 27,
UCharDataTypeId = 28, StringDataTypeId = 29, LongVectorDataTypeId = 30, CompoundDataTypeId = 31,
V2fDataTypeId = 32, V3fDataTypeId = 33, V2dDataTypeId = 34, V3dDataTypeId = 35,
Box2fDataTypeId = 36, Box3fDataTypeId = 37, Box2dDataTypeId = 38, Box3dDataTypeId = 39,
M44fDataTypeId = 40, M44dDataTypeId = 41, QuatfDataTypeId = 42, QuatdDataTypeId = 43,
Color3fDataTypeId = 44, Color4fDataTypeId = 45, Color3dDataTypeId = 46, Color4dDataTypeId = 47,
Color3fVectorDataTypeId = 48, Color4fVectorDataTypeId = 49, Color3dVectorDataTypeId = 50, Color4dVectorDataTypeId = 51,
BlindDataHolderTypeId = 52, RenderableTypeId = 53, ParameterListTypeId = 54, CompoundObjectTypeId = 55,
M33fDataTypeId = 56, M33dDataTypeId = 57, Box2fVectorDataTypeId = 58, Box2dVectorDataTypeId = 59,
BoolDataTypeId = 60, PrimitiveTypeId = 61, PointsPrimitiveTypeId = 62, ImagePrimitiveTypeId = 63,
Box2iDataTypeId = 64, HalfVectorDataTypeId = 65, V2iDataTypeId = 66, MeshPrimitiveTypeId = 67,
ShaderTypeId = 68, RunTimeTypedTypeId = 69, ParameterTypeId = 70, CompoundParameterTypeId = 71,
StringParameterTypeId = 72, ValidatedStringParameterTypeId = 73, FileNameParameterTypeId = 74, IntParameterTypeId = 75,
FloatParameterTypeId = 76, DoubleParameterTypeId = 77, BoolParameterTypeId = 78, V2fParameterTypeId = 79,
V3fParameterTypeId = 80, V2dParameterTypeId = 81, V3dParameterTypeId = 82, Color3fParameterTypeId = 83,
Color4fParameterTypeId = 84, Box2iParameterTypeId = 85, Box2fParameterTypeId = 86, Box3fParameterTypeId = 87,
Box2dParameterTypeId = 88, Box3dParameterTypeId = 89, M44fParameterTypeId = 90, M44dParameterTypeId = 91,
IntVectorParameterTypeId = 92, FloatVectorParameterTypeId = 93, DoubleVectorParameterTypeId = 94, StringVectorParameterTypeId = 95,
V2fVectorParameterTypeId = 96, V3fVectorParameterTypeId = 97, V2dVectorParameterTypeId = 98, V3dVectorParameterTypeId = 99,
Box3fVectorParameterTypeId = 100, Box3dVectorParameterTypeId = 101, M33fVectorParameterTypeId = 102, M44fVectorParameterTypeId = 103,
M33dVectorParameterTypeId = 104, M44dVectorParameterTypeId = 105, QuatfVectorParameterTypeId = 106, QuatdVectorParameterTypeId = 107,
Color3fVectorParameterTypeId = 108, Color4fVectorParameterTypeId = 109, NullObjectTypeId = 110, ParameterisedTypeId = 111,
OpTypeId = 112, ReaderTypeId = 113, WriterTypeId = 114, ImageReaderTypeId = 115,
ImageWriterTypeId = 116, CINImageReaderTypeId = 117, CINImageWriterTypeId = 118, EXRImageReaderTypeId = 119,
EXRImageWriterTypeId = 120, JPEGImageReaderTypeId = 121, JPEGImageWriterTypeId = 122, TIFFImageReaderTypeId = 123,
TIFFImageWriterTypeId = 124, ObjectReaderTypeId = 125, ObjectWriterTypeId = 126, PDCParticleReaderTypeId = 127,
PDCParticleWriterTypeId = 128, PathParameterTypeId = 129, DirNameParameterTypeId = 130, V3iDataTypeId = 131,
RendererTypeId = 132, Box3iDataTypeId = 133, ObjectParameterTypeId = 134, ModifyOpTypeId = 135,
ImageOpTypeId = 136, PrimitiveOpTypeId = 137, ProceduralTypeId = 138, Box3iParameterTypeId = 139,
V2iParameterTypeId = 140, V3iParameterTypeId = 141, ParticleReaderTypeId = 142, ParticleWriterTypeId = 143,
MotionPrimitiveTypeId = 144, DPXImageReaderTypeId = 145, TransformTypeId = 146, MatrixTransformTypeId = 147,
MotionTransformTypeId = 148, MatrixMotionTransformTypeId = 149, GroupTypeId = 150, AttributeStateTypeId = 151,
VisibleRenderableTypeId = 152, StateRenderableTypeId = 153, OBJReaderTypeId = 154, TransformationMatrixfDataTypeId = 155,
TransformationMatrixdDataTypeId = 156, PointNormalsOpTypeId = 157, PointDensitiesOpTypeId = 158, DPXImageWriterTypeId = 159,
BoolVectorDataTypeId = 160, VectorDataFilterOpTypeId = 161, RenderableParameterTypeId = 162, StateRenderableParameterTypeId = 163,
AttributeStateParameterTypeId = 164, ShaderParameterTypeId = 165, TransformParameterTypeId = 166, MatrixMotionTransformParameterTypeId = 167,
MatrixTransformParameterTypeId = 168, VisibleRenderableParameterTypeId = 169, GroupParameterTypeId = 170, MotionPrimitiveParameterTypeId = 171,
PrimitiveParameterTypeId = 172, ImagePrimitiveParameterTypeId = 173, MeshPrimitiveParameterTypeId = 174, PointsPrimitiveParameterTypeId = 175,
PreWorldRenderableTypeId = 176, CameraTypeId = 177, NURBSPrimitiveTypeId = 178, DataCastOpTypeId = 179,
DataPromoteOpTypeId = 180, MatrixMultiplyOpTypeId = 181, PointBoundsOpTypeId = 182, RandomRotationOpTypeId = 183,
V2iVectorDataTypeId = 184, V3iVectorDataTypeId = 185, PointMeshOpTypeId = 186, ParticleMeshOpTypeId = 187,
HalfDataTypeId = 188, MeshPrimitiveOpTypeId = 189, PrimitiveEvaluatorTypeId = 190, MeshPrimitiveEvaluatorTypeId = 191,
MeshPrimitiveImplicitSurfaceOpTypeId = 192, TriangulateOpTypeId = 193, SpherePrimitiveEvaluatorTypeId = 194, SpherePrimitiveTypeId = 195,
ConverterTypeId = 196, ToCoreConverterTypeId = 197, ImageCropOpTypeId = 198, MeshPrimitiveShrinkWrapOpTypeId = 199,
ImagePrimitiveEvaluatorTypeId = 200, FromCoreConverterTypeId = 201, ShortDataTypeId = 202, UShortDataTypeId = 203,
ShortVectorDataTypeId = 204, UShortVectorDataTypeId = 205, PathVectorParameterTypeId = 206, ColorTransformOpTypeId = 207,
TransformOpTypeId = 208, ImageDiffOpTypeId = 209, CurvesPrimitiveTypeId = 210, CoordinateSystemTypeId = 211,
MeshNormalsOpTypeId = 212, MeshMergeOpTypeId = 213, FontTypeId = 214, UniformRandomPointDistributionOpTypeId = 215,
Int64DataTypeId = 216, UInt64DataTypeId = 217, Int64VectorDataTypeId = 218, UInt64VectorDataTypeId = 219,
MappedRandomPointDistributionOpTypeId = 220, PointRepulsionOpTypeId = 221, LuminanceOpTypeId = 222, ImagePrimitiveOpTypeId = 223,
ChannelOpTypeId = 224, SummedAreaOpTypeId = 225, GradeTypeId = 226, Box2iVectorDataTypeId = 227,
Box3iVectorDataTypeId = 228, MedianCutSamplerTypeId = 229, EnvMapSamplerTypeId = 230, MeshVertexReorderOpTypeId = 231,
SplineffDataTypeId = 232, SplineddDataTypeId = 233, SplinefColor3fDataTypeId = 234, SplinefColor4fDataTypeId = 235,
SplineffParameterTypeId = 236, SplineddParameterTypeId = 237, SplinefColor3fParameterTypeId = 238, SplinefColor4fParameterTypeId = 239,
CompoundObjectParameterTypeId = 240, DisplayDriverTypeId = 241, DisplayDriverCreatorTypeId = 242, ImageDisplayDriverTypeId = 243,
DisplayDriverServerTypeId = 244, ClientDisplayDriverTypeId = 245, SplineToImageTypeId = 246, DisplayTypeId = 247,
MeshTangentsOpTypeId = 248, WarpOpTypeId = 249, UVDistortOpTypeId = 250, LinearToSRGBOpTypeId = 251,
SRGBToLinearOpTypeId = 252, LinearToCineonOpTypeId = 253, CineonToLinearOpTypeId = 254, CubeColorTransformOpTypeId = 255,
CubeColorLookupfDataTypeId = 256, CubeColorLookupdDataTypeId = 257, CubeColorLookupfParameterTypeId = 258, CubeColorLookupdParameterTypeId = 259,
BoolVectorParameterTypeId = 260, LinearToRec709OpTypeId = 261, Rec709ToLinearOpTypeId = 262, ObjectVectorTypeId = 263,
ObjectVectorParameterTypeId = 264, YUVImageWriterTypeId = 265, ImageCompositeOpTypeId = 266, ImagePremultiplyOpTypeId = 267,
ImageUnpremultiplyOpTypeId = 268, DateTimeDataTypeId = 269, DateTimeParameterTypeId = 270, SGIImageReaderTypeId = 271,
TimeDurationDataTypeId = 272, TimeDurationParameterTypeId = 273, TimePeriodDataTypeId = 274, TimePeriodParameterTypeId = 275,
PatchMeshPrimitiveTypeId = 276, CurvesPrimitiveParameterTypeId = 277, CurveExtrudeOpTypeId = 278, FrameListTypeId = 279,
EmptyFrameListTypeId = 280, FrameRangeTypeId = 281, CompoundFrameListTypeId = 282, ReorderedFrameListTypeId = 283,
BinaryFrameListTypeId = 284, ReversedFrameListTypeId = 285, ExclusionFrameListTypeId = 286, FrameListParameterTypeId = 287,
FileSequenceTypeId = 288, FileSequenceParameterTypeId = 289, FileSequenceVectorParameterTypeId = 290, ParameterisedProceduralTypeId = 291,
ColorSpaceTransformOpTypeId = 292, TGAImageReaderTypeId = 293, TGAImageWriterTypeId = 294, BINParticleReaderTypeId = 295,
BINParticleWriterTypeId = 296, BINMeshReaderTypeId = 297, BGEOParticleReaderTypeId = 298, NParticleReaderTypeId = 299,
IFFImageReaderTypeId = 300, IFFHairReaderTypeId = 301, FaceAreaOpTypeId = 302, CurvesMergeOpTypeId = 303,
CurvesPrimitiveOpTypeId = 304, CurvesPrimitiveEvaluatorTypeId = 305, HdrMergeOpTypeId = 306, HitMissTransformTypeId = 307,
CurveTracerTypeId = 308, ImageThinnerTypeId = 309, CurveLineariserTypeId = 310, CompoundDataBaseTypeId = 311,
ImageConvolveOpTypeId = 312, ClassParameterTypeId = 313, ClassVectorParameterTypeId = 314, CurveTangentsOpTypeId = 315,
MarschnerParameterTypeId = 316, MarschnerLookupTableOpTypeId = 317, SmoothSkinningDataTypeId = 318, FaceVaryingPromotionOpTypeId = 319,
MeshDistortionsOpTypeId = 320, PointVelocityDisplaceOpTypeId = 321, SmoothSkinningDataParameterTypeId = 322, CompressSmoothSkinningDataOpTypeId = 323,
DecompressSmoothSkinningDataOpTypeId = 324, NormalizeSmoothSkinningWeightsOpTypeId = 325, ReorderSmoothSkinningInfluencesOpTypeId = 326, RemoveSmoothSkinningInfluencesOpTypeId = 327,
SmoothSmoothSkinningWeightsOpTypeId = 328, MixSmoothSkinningWeightsOpTypeId = 329, PointSmoothSkinningOpTypeId = 330, AddSmoothSkinningInfluencesOpTypeId = 331,
LimitSmoothSkinningInfluencesOpTypeId = 332, PointsPrimitiveEvaluatorTypeId = 333, TransformationMatrixfParameterTypeId = 334, TransformationMatrixdParameterTypeId = 335,
PointsMotionOpTypeId = 336, CapturingRendererTypeId = 337, LinearToPanalogOpTypeId = 338, PanalogToLinearOpTypeId = 339,
EnvMapSHProjectorTypeId = 340, LightTypeId = 341, ContrastSmoothSkinningWeightsOpTypeId = 342, PointDistributionOpTypeId = 343,
LineSegment3fDataTypeId = 344, LineSegment3dDataTypeId = 345, LineSegment3fParameterTypeId = 346, LineSegment3dParameterTypeId = 347,
DataInterleaveOpTypeId = 348, DataConvertOpTypeId = 349, PNGImageReaderTypeId = 350, DeepImageReaderTypeId = 351,
DeepImageWriterTypeId = 352, DeepImageConverterTypeId = 353, LastCoreTypeId = 99999, FirstExtensionTypeId = 100000,
FirstCoreDynamicsTypeId = 104000, LastCoreDynamicsTypeId = 104999, FirstCoreGLTypeId = 105000, LastCoreGLTypeId = 105999,
FirstCoreRITypeId = 106000, LastCoreRITypeId = 106999, FirstCoreNukeTypeId = 107000, LastCoreNukeTypeId = 107999,
FirstCoreTruelightTypeId = 108000, LastCoreTruelightTypeId = 108999, FirstCoreMayaTypeId = 109000, LastCoreMayaTypeId = 109999,
FirstGafferTypeId = 110000, LastGafferTypeId = 110999, FirstCoreArnoldTypeId = 111000, LastCoreArnoldTypeId = 111999,
FirstDynamicTypeId = 300000, LastDynamicTypeId = 399999, LastExtensionTypeId = 399999
}
Functions
IE_CORE_DECLAREPTR (AddSmoothSkinningInfluencesOp)
template<typename T >
T degreesToRadians (const T &value)
template<typename T >
T radiansToDegrees (const T &value)
IE_CORE_FORWARDDECLARE (CompoundObject)
IE_CORE_DECLAREPTR (AttributeCache)
IE_CORE_DECLAREPTR (AttributeState)
template<typename Vec , typename F >
void bezierSubdivide (const Vec &v0, const Vec &v1, const Vec &v2, const Vec &v3, typename Vec::BaseType tolerance, F &f)
template<typename Vec , typename F >
void bezierSubdivide (const Vec &v0, const Vec &v1, const Vec &v2, typename Vec::BaseType tolerance, F &f)
As above but for quadratic curves.
IE_CORE_DECLAREPTR (BGEOParticleReader)
IE_CORE_DECLAREPTR (BinaryFrameList)
IE_CORE_FORWARDDECLARE (MeshPrimitive)
IE_CORE_DECLAREPTR (BINMeshReader)
IE_CORE_DECLAREPTR (BINParticleWriter)
template<class T >
std::ostream & operator<< (std::ostream &os, const Imath::Box< T > &obj)
Streaming for Imath::Box types.
template<class T >
Imath::Vec2< T > closestPointInBox (const Imath::Vec2< T > &p, const Imath::Box< Imath::Vec2< T > > &box)
Closest point in box for 2D box types.
template<typename T >
BoxTraits< T >::BaseType boxSize (const T &box)
Returns a vector representing the length of each side of the box.
template<typename T >
BoxTraits< T >::BaseType boxCenter (const T &box)
Returns the center point of the box.
template<typename T >
void boxExtend (T &box, const typename BoxTraits< T >::BaseType &p)
Extends the box by the given point.
template<typename T >
void boxExtend (T &box, const T &box2)
Extends the box by the given box.
template<typename T >
T boxIntersection (const T &box, const T &box2)
Returns the intersection between two boxes, or the empty box if there is no intersection.
template<typename T >
bool boxIntersects (const T &box, const typename BoxTraits< T >::BaseType &p)
Returns true if the box intersects (contains) the given point.
template<typename T >
bool boxIntersects (const T &box, const T &box2)
Returns true if the box intersects the given box.
template<typename T >
bool boxContains (const T &box, const T &containee)
Returns true if box contains containee.
template<typename T >
bool boxIntersects (const T &box, const typename BoxTraits< T >::BaseType &origin, const typename BoxTraits< T >::BaseType &direction, typename BoxTraits< T >::BaseType &result)
template<typename T >
void boxSplit (const T &box, T &low, T &high, int axis)
Splits the box into two across the specified axis.
template<typename T >
void boxSplit (const T &box, T &low, T &high)
Splits the box into two across the major axis.
template<typename T >
int boxMajorAxis (const T &box)
Returns the longest axis of the box.
bool littleEndian ()
bool bigEndian ()
template<typename T >
T reverseBytes (const T &x)
Returns a copy of x with reversed byte order.
template<>
char reverseBytes< char > (const char &x)
template<>
unsigned char reverseBytes< unsigned char > (const unsigned char &x)
template<>
int16_t reverseBytes< int16_t > (const int16_t &x)
template<>
uint16_t reverseBytes< uint16_t > (const uint16_t &x)
template<>
int32_t reverseBytes< int32_t > (const int32_t &x)
template<>
uint32_t reverseBytes< uint32_t > (const uint32_t &x)
template<>
float reverseBytes< float > (const float &x)
template<>
Imf::Int64 reverseBytes< Imf::Int64 > (const Imf::Int64 &x)
template<>
double reverseBytes< double > (const double &x)
template<typename T >
T asLittleEndian (const T &x)
template<typename T >
T asBigEndian (const T &x)
IE_CORE_FORWARDDECLARE (CachedReader)
IE_CORE_FORWARDDECLARE (ModifyOp)
IE_CORE_FORWARDDECLARE (Object)
IE_CORE_DECLAREPTR (Camera)
IE_CORE_DECLAREPTR (ChannelOp)
IE_CORE_DECLAREPTR (CineonToLinearOp)
IE_CORE_DECLAREPTR (CINImageReader)
IE_CORE_DECLAREPTR (CINImageWriter)
template<typename T , typename S >
T::BaseType luminance (const T &color, const S &weights)
Compute the luminance of a color using the given set of weights.
template<typename T >
T::BaseType luminance (const T &color)
template<typename T >
T adjustSaturation (const T &color, typename T::BaseType saturation)
template<typename T >
T linearToSRGB (const T &color)
template<typename T >
T sRGBToLinear (const T &color)
IE_CORE_DECLAREPTR (ColorSpaceTransformOp)
IE_CORE_DECLAREPTR (ColorTransformOp)
template<typename T >
T compositeOver (T aVal, T aAlpha, T bVal, T bAlpha)
A over B.
template<typename T >
T compositeMax (T aVal, T aAlpha, T bVal, T bAlpha)
max(A, B)
template<typename T >
T compositeMin (T aVal, T aAlpha, T bVal, T bAlpha)
min(A, B)
template<typename T >
T compositeMultiply (T aVal, T aAlpha, T bVal, T bAlpha)
A*B.
IE_CORE_DECLAREPTR (CompoundData)
IE_CORE_DECLAREPTR (CompoundDataBase)
IE_CORE_DECLAREPTR (CompoundFrameList)
IE_CORE_DECLAREPTR (CompoundMessageHandler)
IE_CORE_DECLAREPTR (CompoundObject)
IE_CORE_DECLAREPTR (CompoundParameter)
IE_CORE_DECLAREPTR (CompressSmoothSkinningDataOp)
IE_CORE_DECLAREPTR (ContrastSmoothSkinningWeightsOp)
template<typename T , typename F >
T convert (const F &from)
IE_CORE_DECLAREPTR (Converter)
IE_CORE_DECLAREPTR (CoordinateSystem)
IE_CORE_DECLAREPTR (CubeColorLookupfParameter)
IE_CORE_DECLAREPTR (CubeColorTransformOp)
IE_CORE_DECLAREPTR (CurveExtrudeOp)
IE_CORE_DECLAREPTR (CurveLineariser)
IE_CORE_DECLAREPTR (CurvesMergeOp)
IE_CORE_DECLAREPTR (CurvesPrimitive)
IE_CORE_DECLAREPTR (CurvesPrimitiveEvaluator)
IE_CORE_DECLAREPTR (CurveTangentsOp)
IE_CORE_DECLAREPTR (CurveTracer)
IE_CORE_DECLAREPTR (Data)
IE_CORE_DECLAREPTR (DataCastOp)
IE_CORE_DECLAREPTR (DataConvertOp)
IE_CORE_DECLAREPTR (DataInterleaveOp)
IE_CORE_DECLAREPTR (DataPromoteOp)
IE_CORE_DECLAREPTR (DecompressSmoothSkinningDataOp)
IE_CORE_FORWARDDECLARE (FileNameParameter)
IE_CORE_DECLAREPTR (DeepImageConverter)
IE_CORE_DECLAREPTR (DeepImageReader)
IE_CORE_FORWARDDECLARE (DeepImageWriter)
IE_CORE_DECLAREPTR (DeepImageWriter)
IE_CORE_DECLAREPTR (DeepPixel)
template<class Functor , template< typename > class Enabler, typename ErrorHandler >
Functor::ReturnType despatchTypedData (const DataPtr &data, Functor &functor, ErrorHandler &errorHandler)
template<class Functor , template< typename > class Enabler, typename ErrorHandler >
Functor::ReturnType despatchTypedData (const DataPtr &data, Functor &functor)
Convenience version of despatchTypedData which constructs an ErrorHandler using its default constructor.
template<class Functor , template< typename > class Enabler, typename ErrorHandler >
Functor::ReturnType despatchTypedData (const DataPtr &data)
Convenience version of despatchTypedData which constructs the ErrorHandler and Functor using their default constructors.
template<class Functor , template< typename > class Enabler>
Functor::ReturnType despatchTypedData (const DataPtr &data, Functor &functor)
template<class Functor , template< typename > class Enabler>
Functor::ReturnType despatchTypedData (const DataPtr &data)
template<class Functor >
Functor::ReturnType despatchTypedData (const DataPtr &data, Functor &functor)
template<class Functor >
Functor::ReturnType despatchTypedData (const DataPtr &data)
template<template< typename > class Trait>
bool despatchTraitsTest (const DataPtr &data)
IE_CORE_DECLAREPTR (Display)
IE_CORE_FORWARDDECLARE (DisplayDriver)
IE_CORE_DECLAREPTR (DPXImageReader)
IE_CORE_DECLAREPTR (DPXImageWriter)
IE_CORE_DECLAREPTR (EmptyFrameList)
IE_CORE_DECLAREPTR (EnvMapSampler)
IE_CORE_FORWARDDECLARE (ObjectParameter)
IE_CORE_DECLAREPTR (EnvMapSHProjector)
IE_CORE_DECLAREPTR (ExclusionFrameList)
IE_CORE_DECLAREPTR (EXRImageReader)
IE_CORE_DECLAREPTR (EXRImageWriter)
IE_CORE_DECLAREPTR (FaceAreaOp)
IE_CORE_DECLAREPTR (FaceVaryingPromotionOp)
int fastFloat2Int (double v)
int fastFloatRound (double v)
int fastFloatFloor (double v)
int fastFloatCeil (double v)
IE_CORE_FORWARDDECLARE (FileSequence)
void findSequences (const std::vector< std::string > &names, std::vector< FileSequencePtr > &sequences)
void findSequences (const std::vector< std::string > &names, std::vector< FileSequencePtr > &sequences, size_t minSequenceSize)
void ls (const std::string &path, std::vector< FileSequencePtr > &sequences, size_t minSequenceSize=2)
Generates all sequences with at least minSequenceSize elements residing in given directory in the form of a list of FileSequences.
void ls (const std::string &sequencePath, FileSequencePtr &sequence, size_t minSequenceSize=2)
Attempts to find a sequence matching the given sequence template (e.g. with at least one '#' character).
FrameListPtr frameListFromList (const std::vector< FrameList::Frame > &frames)
IE_CORE_DECLAREPTR (FileSequenceParameter)
IE_CORE_DECLAREPTR (FileSequenceVectorParameter)
IE_CORE_DECLAREPTR (FilteredMessageHandler)
IE_CORE_FORWARDDECLARE (ImagePrimitive)
IE_CORE_FORWARDDECLARE (Group)
IE_CORE_DECLAREPTR (Font)
IE_CORE_FORWARDDECLARE (FrameList)
IE_CORE_DECLAREPTR (FrameListParameter)
IE_CORE_DECLAREPTR (FrameRange)
IE_CORE_DECLAREPTR (FromCoreConverter)
IE_CORE_DECLAREPTR (Grade)
IE_CORE_DECLAREPTR (HdrMergeOp)
template<typename Vec >
Vec::BaseType henyeyGreenstein (typename Vec::BaseType g, const Vec &incident, const Vec &outgoing)
Vectors must be normalized already.
template<typename T >
T henyeyGreenstein (T g, T theta)
Theta in radians.
template<typename T >
T henyeyGreensteinCT (T g, T cosTheta)
template<typename T , typename OutputIterator >
void decToHex (T value, OutputIterator result)
template<typename InputIterator , typename OutputIterator >
void decToHex (InputIterator first, InputIterator last, OutputIterator result)
template<typename RandomAccessIterator >
std::string decToHex (RandomAccessIterator first, RandomAccessIterator last)
template<typename T >
std::string decToHex (T n)
template<typename T , typename InputIterator >
T hexToDec (InputIterator first, InputIterator last)
template<typename T >
T hexToDec (const std::string &s)
template<typename T , typename InputIterator , typename OutputIterator >
void hexToDec (InputIterator first, InputIterator last, OutputIterator result)
IE_CORE_FORWARDDECLARE (IndexedIOInterface)
IE_CORE_FORWARDDECLARE (HierarchicalCacheDependency)
IE_CORE_DECLAREPTR (HierarchicalCache)
IE_CORE_DECLAREPTR (HitMissTransform)
int majorVersion ()
Returns the major version for the IECore library.
int minorVersion ()
Returns the minor version for the IECore library.
int patchVersion ()
Returns the patch version for the IECore library.
const std::string & versionString ()
Returns a string of the form "major.minor.patch".
bool withASIO ()
Returns true if IECore was built with boost::asio support.
bool withBoostFactorial ()
Returns true if IECore was built with boost::math::factorial support.
bool withTIFF ()
Returns true if IECore was built with TIFF support.
bool withJPEG ()
Returns true if IECore was built with JPEG support.
bool withFreeType ()
Returns true if IECore was built with FreeType suppport.
bool withPNG ()
Returns true if IECore was built with PNG suppport.
IE_CORE_FORWARDDECLARE (IFFFile)
IE_CORE_FORWARDDECLARE (CurvesPrimitive)
IE_CORE_DECLAREPTR (IFFHairReader)
IE_CORE_DECLAREPTR (ImageCompositeOp)
IE_CORE_DECLAREPTR (ImageConvolveOp)
IE_CORE_DECLAREPTR (ImageCropOp)
IE_CORE_DECLAREPTR (ImageDiffOp)
IE_CORE_DECLAREPTR (ImagePremultiplyOp)
IE_CORE_DECLAREPTR (ImagePrimitive)
IE_CORE_DECLAREPTR (ImagePrimitiveEvaluator)
IE_CORE_DECLAREPTR (ImageReader)
IE_CORE_DECLAREPTR (ImageThinner)
IE_CORE_DECLAREPTR (ImageUnpremultiplyOp)
IE_CORE_DECLAREPTR (ImageWriter)
IE_CORE_FORWARDDECLARE (IndexedIOFilter)
IE_CORE_DECLAREPTR (IndexedIONullFilter)
IE_CORE_DECLAREPTR (IndexedIOEntryTypeFilter)
IE_CORE_DECLAREPTR (IndexedIORegexFilter)
IE_CORE_DECLAREPTR (InterpolatedCache)
template<class T , class U >
bool operator== (T *a, IntrusivePtr< U > const &b)
template<class T , class U >
bool operator!= (T *a, IntrusivePtr< U > const &b)
template<class T >
void swap (IntrusivePtr< T > &lhs, IntrusivePtr< T > &rhs)
template<class T >
T * get_pointer (IntrusivePtr< T > const &p)
template<class T , class U >
IntrusivePtr< T > staticPointerCast (IntrusivePtr< U > const &p)
template<class T , class U >
IntrusivePtr< T > constPointerCast (IntrusivePtr< U > const &p)
template<class T , class U >
IntrusivePtr< T > dynamicPointerCast (IntrusivePtr< U > const &p)
template<class E , class T , class Y >
std::basic_ostream< E, T > & operator<< (std::basic_ostream< E, T > &os, IntrusivePtr< Y > const &p)
IE_CORE_DECLAREPTR (JPEGImageReader)
IE_CORE_DECLAREPTR (JPEGImageWriter)
IE_CORE_DECLAREPTR (LevelFilteredMessageHandler)
IE_CORE_DECLAREPTR (Light)
IE_CORE_DECLAREPTR (LimitSmoothSkinningInfluencesOp)
IE_CORE_DECLAREPTR (LinearToCineonOp)
IE_CORE_DECLAREPTR (LinearToPanalogOp)
IE_CORE_DECLAREPTR (LinearToRec709Op)
IE_CORE_DECLAREPTR (LinearToSRGBOp)
template<class T >
std::ostream & operator<< (std::ostream &o, const LineSegment< T > &lineSegment)
IE_CORE_DECLAREPTR (LuminanceOp)
IE_CORE_DECLAREPTR (MappedRandomPointDistributionOp)
IE_CORE_DECLAREPTR (MarschnerLookupTableOp)
template<typename T >
int sign (T x)
Returns -1 for negative numbers, 1 for positive, and 0 for 0.
template<typename T >
T smoothstep (T v0, T v1, T x)
Computes smoothstep function from Ken Perlin's original noise implementation.
template<typename T >
Imath::Matrix44< T > matrixFromBasis (const Imath::Vec3< T > &x, const Imath::Vec3< T > &y, const Imath::Vec3< T > &z, const Imath::Vec3< T > &o)
template<class T >
float determinant (const Imath::Matrix33< T > &m)
template<class T >
float determinant (const Imath::Matrix44< T > &m)
template<>
Imath::M44d convert (const Imath::M44f &in)
template<>
Imath::M44f convert (const Imath::M44d &in)
IE_CORE_DECLAREPTR (MatrixMotionTransform)
IE_CORE_DECLAREPTR (MatrixMultiplyOp)
template<typename T >
void matSet (T &m, unsigned int i, unsigned int j, typename MatrixTraits< T >::BaseType x)
Sets the specified component of m to the value x.
template<typename T >
void matSetAll (T &m, typename MatrixTraits< T >::BaseType x)
Sets all components of m to the value x.
template<typename T >
MatrixTraits< T >::BaseType matGet (const T &m, unsigned int i, unsigned int j)
Returns the value of the specified component of v.
template<typename T , typename S >
S matConvert (const T &m)
Converts from one matrix type to another.
template<typename T , typename S >
void matConvert (const T &m1, S &m2)
Converts from one matrix type to another.
IE_CORE_DECLAREPTR (MatrixTransform)
IE_CORE_DECLAREPTR (MedianCutSampler)
IE_CORE_DECLAREPTR (MeshDistortionsOp)
IE_CORE_DECLAREPTR (MeshMergeOp)
IE_CORE_DECLAREPTR (MeshNormalsOp)
IE_CORE_DECLAREPTR (MeshPrimitiveBuilder)
IE_CORE_DECLAREPTR (MeshPrimitiveEvaluator)
IE_CORE_DECLAREPTR (MeshPrimitiveImplicitSurfaceFunction)
IE_CORE_DECLAREPTR (MeshPrimitiveImplicitSurfaceOp)
IE_CORE_DECLAREPTR (MeshPrimitiveShrinkWrapOp)
IE_CORE_DECLAREPTR (MeshTangentsOp)
IE_CORE_DECLAREPTR (MeshVertexReorderOp)
IE_CORE_DECLAREPTR (MessageHandler)
void msg (MessageHandler::Level level, const std::string &context, const std::string &message)
void msg (MessageHandler::Level level, const std::string &context, const boost::format &message)
IE_CORE_DECLAREPTR (MixSmoothSkinningWeightsOp)
IE_CORE_DECLAREPTR (ModifyOp)
IE_CORE_DECLAREPTR (MotionPrimitive)
std::ostream & operator<< (std::ostream &o, const MurmurHash &hash)
IE_CORE_DECLAREPTR (NormalizeSmoothSkinningWeightsOp)
IE_CORE_DECLAREPTR (NParticleReader)
IE_CORE_DECLAREPTR (NullMessageHandler)
IE_CORE_DECLAREPTR (IntParameter)
IE_CORE_DECLAREPTR (NURBSPrimitive)
ObjectPtr linearObjectInterpolation (const ObjectPtr &y0, const ObjectPtr &y1, double x)
Utility function that applies linear interpolation on objects. Returns a "null" pointer if the Object cannot be interpolated.
ObjectPtr cubicObjectInterpolation (const ObjectPtr &y0, const ObjectPtr &y1, const ObjectPtr &y2, const ObjectPtr &y3, double x)
Utility function that applies cubic interpolation on objects. Returns a "null" pointer if the Object cannot be interpolated.
IE_CORE_DECLAREPTR (ObjectParameter)
IE_CORE_DECLAREPTR (ObjectReader)
IE_CORE_DECLAREPTR (ObjectWriter)
IE_CORE_DECLAREPTR (OBJReader)
IE_CORE_FORWARDDECLARE (Parameter)
IE_CORE_DECLAREPTR (Op)
IE_CORE_DECLAREPTR (OStreamMessageHandler)
IE_CORE_DECLAREPTR (PanalogToLinearOp)
IE_CORE_DECLAREPTR (Parameter)
IE_CORE_DECLAREPTR (Parameterised)
IE_CORE_FORWARDDECLARE (CompoundParameter)
IE_CORE_DECLAREPTR (ParameterisedProcedural)
IE_CORE_DECLAREPTR (ParticleMeshOp)
IE_CORE_DECLAREPTR (ParticleReader)
IE_CORE_FORWARDDECLARE (PointsPrimitive)
IE_CORE_DECLAREPTR (ParticleWriter)
IE_CORE_DECLAREPTR (PatchMeshPrimitive)
IE_CORE_DECLAREPTR (PDCParticleReader)
IE_CORE_DECLAREPTR (PDCParticleWriter)
IE_CORE_DECLAREPTR (PNGImageReader)
IE_CORE_DECLAREPTR (PointBoundsOp)
IE_CORE_DECLAREPTR (PointDensitiesOp)
IE_CORE_DECLAREPTR (PointDistributionOp)
IE_CORE_DECLAREPTR (PointMeshOp)
IE_CORE_DECLAREPTR (PointNormalsOp)
IE_CORE_DECLAREPTR (PointRepulsionOp)
IE_CORE_DECLAREPTR (PointSmoothSkinningOp)
IE_CORE_DECLAREPTR (PointsMotionOp)
IE_CORE_DECLAREPTR (PointsPrimitive)
IE_CORE_DECLAREPTR (PointsPrimitiveEvaluator)
IE_CORE_DECLAREPTR (PointVelocityDisplaceOp)
template<typename Iterator >
std::iterator_traits< Iterator >
::value_type polygonNormal (Iterator first, Iterator last)
template<typename Iterator >
std::iterator_traits< Iterator >
::value_type polygonNormal (Iterator first, Iterator last, bool normalized)
As above, but only normalizes the normal if normalised==true.
template<typename Iterator >
Winding polygonWinding (Iterator first, Iterator last)
template<typename Iterator >
Winding polygonWinding (Iterator first, Iterator last, const typename std::iterator_traits< Iterator >::value_type &viewVector)
template<typename Iterator >
Imath::Box< typename
std::iterator_traits< Iterator >
::value_type > polygonBound (Iterator first, Iterator last)
Returns the bounding box of the polygon specified by the vertices in the given iterator range.
template<typename Iterator >
std::iterator_traits< Iterator >
::value_type::BaseType polygonArea (Iterator first, Iterator last)
Returns the area of the polygon specified by the vertices in the given iterator range.
IE_CORE_DECLAREPTR (PreWorldRenderable)
IE_CORE_DECLAREPTR (Primitive)
IE_CORE_FORWARDDECLARE (PrimitiveEvaluator)
IE_CORE_DECLAREPTR (PrimitiveEvaluator)
IE_CORE_DECLAREPTR (PrimitiveImplicitSurfaceFunction)
IE_CORE_DECLAREPTR (PrimitiveOp)
template<class T >
T sinx_over_x (T x)
template<class T >
T angle4D (const Imath::Quat< T > &q1, const Imath::Quat< T > &q2)
template<class T >
Imath::Quat< T > slerp (const Imath::Quat< T > &q1, const Imath::Quat< T > &q2, T t)
template<class T >
Imath::Quat< T > slerpShortestArc (const Imath::Quat< T > &q1, const Imath::Quat< T > &q2, T t)
template<class Vec , class Rand >
Vec barycentricRand (Rand &rand)
Returns a random barycentric coordinate.
template<class Vec , class Rand >
Vec triangleRand (const Vec &v0, const Vec &v1, const Vec &v2, Rand &rand)
Returns a random point within the specified triangle.
template<class Vec , class Rand >
Vec cosineHemisphereRand (Rand &rand)
IE_CORE_DECLAREPTR (RandomRotationOp)
IE_CORE_FORWARDDECLARE (Reader)
IE_CORE_DECLAREPTR (Rec709ToLinearOp)
void intrusive_ptr_add_ref (const IECore::RefCounted *r)
Functions required to allow use of RefCounted with IntrusivePtr.
void intrusive_ptr_release (const IECore::RefCounted *r)
IE_CORE_DECLAREPTR (RemoveSmoothSkinningInfluencesOp)
IE_CORE_FORWARDDECLARE (Renderer)
IE_CORE_DECLAREPTR (Renderable)
IE_CORE_DECLAREPTR (ReorderedFrameList)
IE_CORE_DECLAREPTR (ReorderSmoothSkinningInfluencesOp)
IE_CORE_DECLAREPTR (ReversedFrameList)
IE_CORE_DECLAREPTR (RunTimeTyped)
template<typename T , typename S >
IntrusivePtr< T > runTimeCast (const IntrusivePtr< S > &src)
template<typename T , typename S >
T * runTimeCast (S *src)
template<typename T , typename S >
IntrusivePtr< T > assertedStaticCast (const IntrusivePtr< S > &src)
template<typename T , typename S >
T * assertedStaticCast (S *src)
IE_CORE_DECLAREPTR (SGIImageReader)
IE_CORE_DECLAREPTR (Shader)
IE_CORE_DECLAREPTR (SimpleSubsurface)
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION (BoolData, bool)
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION (FloatData, float)
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION (DoubleData, double)
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION (IntData, int)
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION (UIntData, unsigned int)
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION (CharData, char)
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION (HalfData, half)
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION (ShortData, short)
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION (Int64Data, int64_t)
IE_CORE_DEFINETYPEDDATATRAITSSPECIALIZATION (UInt64Data, uint64_t)
IE_CORE_DECLAREPTR (SmoothSmoothSkinningWeightsOp)
IE_CORE_DECLAREPTR (SpherePrimitive)
IE_CORE_DECLAREPTR (SpherePrimitiveEvaluator)
template<class S >
SphericalHarmonics< S > operator+ (const SphericalHarmonics< S > &lsh, const SphericalHarmonics< S > &rsh)
template<class S >
const SphericalHarmonics< S > & operator+= (SphericalHarmonics< S > &lsh, const SphericalHarmonics< S > &rsh)
template<class S >
SphericalHarmonics< S > operator- (const SphericalHarmonics< S > &lsh, const SphericalHarmonics< S > &rsh)
template<class S >
const SphericalHarmonics< S > & operator-= (SphericalHarmonics< S > &lsh, const SphericalHarmonics< S > &rsh)
template<class S , class T >
SphericalHarmonics< S > operator* (const SphericalHarmonics< S > &lsh, const T &scale)
template<class S , class T >
const SphericalHarmonics< S > & operator*= (SphericalHarmonics< S > &lsh, const T &scale)
template<class S , class T >
SphericalHarmonics< S > operator* (const SphericalHarmonics< S > &sh1, const SphericalHarmonics< T > &sh2)
template<class S , class T >
const SphericalHarmonics< S > operator*= (SphericalHarmonics< S > &sh1, const SphericalHarmonics< T > &sh2)
template<class T >
SphericalHarmonics< T > lambertianKernel (unsigned int bands, bool normalized=false)
template<class T >
SphericalHarmonics< T > rotatedKernel (const SphericalHarmonics< T > &kernel, const Imath::V3f &direction)
template<class T >
void windowingFilter (SphericalHarmonics< T > &sh, float windowSize)
template<class S , class T >
const SphericalHarmonics< S > & operator*= (SphericalHarmonics< S > &sh, const SphericalHarmonicsRotationMatrix< T > &m)
template<class S , class T >
const SphericalHarmonics< S > & operator*= (SphericalHarmonics< S > &sh, const SphericalHarmonicsTransferMatrix< T > &m)
IE_CORE_DECLAREPTR (SplineToImage)
IE_CORE_DECLAREPTR (SRGBToLinearOp)
IE_CORE_DECLAREPTR (StateRenderable)
template<class Iterator >
std::iterator_traits< Iterator >
::value_type join (Iterator begin, Iterator end, const typename std::iterator_traits< Iterator >::reference separator)
template<class String >
bool isUpperCase (const String &s)
template<class String >
bool isLowerCase (const String &s)
IE_CORE_DECLAREPTR (SummedAreaOp)
template<template< typename > class Predicate>
bool testTypedData (DataPtr data)
template<typename Vec >
VectorTraits< Vec >::BaseType tetrahedronVolume (const Vec &v0, const Vec &v1, const Vec &v2, const Vec &v3)
Returns the volume of the tetrahedron defined by the 4 specified vertices.
template<typename Vec >
Vec tetrahedronPoint (const Vec &v0, const Vec &v1, const Vec &v2, const Vec &v3, typename VectorTraits< Vec >::BaseType barycentric[4])
Returns the point of the tetrahedron which has the given barycentric coordinates.
template<typename Vec >
void tetrahedronBarycentric (const Vec &v0, const Vec &v1, const Vec &v2, const Vec &v3, const Vec &p, typename VectorTraits< Vec >::BaseType barycentric[4])
template<typename Vec >
VectorTraits< Vec >::BaseType tetrahedronClosestBarycentric (const Vec &v0, const Vec &v1, const Vec &v2, const Vec &v3, const Vec &p, typename VectorTraits< Vec >::BaseType barycentric[4])
Returns the squared-distance to the closest point on the tetrahedron, and computes that point's barycentric coordinates.
Imath::V3i tetrahedronFaceIndices (int face)
IE_CORE_DECLAREPTR (TGAImageReader)
IE_CORE_DECLAREPTR (TGAImageWriter)
IE_CORE_DECLAREPTR (TIFFImageReader)
IE_CORE_DECLAREPTR (TIFFImageWriter)
IE_CORE_DECLAREPTR (ToCoreConverter)
IE_CORE_DECLAREPTR (Transform)
template<class T >
std::ostream & operator<< (std::ostream &os, const TransformationMatrix< T > &x)
IE_CORE_DECLAREPTR (TransformOp)
template<class Vec >
VectorTraits< Vec >::BaseType triangleArea (const Vec &v0, const Vec &v1, const Vec &v2)
template<class Vec >
Vec triangleNormal (const Vec &v0, const Vec &v1, const Vec &v2)
template<class Vec >
Vec trianglePoint (const Vec &v0, const Vec &v1, const Vec &v2, const Imath::Vec3< typename VectorTraits< Vec >::BaseType > &barycentric)
template<class Vec >
VectorTraits< Vec >::BaseType triangleClosestBarycentric (const Vec &v0, const Vec &v1, const Vec &v2, const Vec &p, Imath::Vec3< typename VectorTraits< Vec >::BaseType > &barycentric)
Returns the squared-distance to the closest point on the triangle, and places that point's barycentric coordinates in the 4th argument.
template<class Vec >
Vec triangleClosestPoint (const Vec &v0, const Vec &v1, const Vec &v2, const Vec &p, Imath::Vec3< typename VectorTraits< Vec >::BaseType > &barycentric)
Returns the closest point on the triangle, and places that point's barycentric coordinates in the 4th argument.
template<class Vec >
int triangleBarycentricFeature (const Vec &barycentric, typename VectorTraits< Vec >::BaseType tolerance=1.e-6)
template<class Vec >
int triangleClosestFeature (const Vec &v0, const Vec &v1, const Vec &v2, const Vec &p)
Returns the closest feature on the triangle to the given point. The return values are as barycentricFeature.
template<class Vec >
bool triangleContainsPoint (const Vec &v0, const Vec &v1, const Vec &v2, const Vec &p)
template<class Vec >
bool triangleContainsPoint (const Vec &v0, const Vec &v1, const Vec &v2, const Vec &p, Imath::Vec3< typename VectorTraits< Vec >::BaseType > &barycentric)
template<class Vec >
bool triangleRayIntersection (const Vec &v0, const Vec &v1, const Vec &v2, const Vec &origin, const Vec &dir, Vec &pt, Vec &barycentric, bool &front)
IE_CORE_DECLAREPTR (TriangulateOp)
IE_CORE_DECLAREPTR (RenderableParameter)
IE_CORE_DECLAREPTR (UniformRandomPointDistributionOp)
IE_CORE_DECLAREPTR (UVDistortOp)
IE_CORE_DECLAREPTR (VectorDataFilterOp)
template<typename T >
void vecSet (T &v, unsigned int i, typename VectorTraits< T >::BaseType x)
Sets the ith component of v to the value x.
template<typename T >
void vecSetAll (T &v, typename VectorTraits< T >::BaseType x)
Sets all components of v to the value x.
template<typename T >
VectorTraits< T >::BaseType vecGet (const T &v, unsigned int i)
Returns the value of the ith component of v.
template<typename T >
T vecAdd (const T &v1, const T &v2)
Adds v1 to v2 returning a new vector.
template<typename T >
void vecAdd (const T &v1, const T &v2, T &result)
template<typename T >
T vecSub (const T &v1, const T &v2)
Subtracts v2 from v1, returning a new vector.
template<typename T >
void vecSub (const T &v1, const T &v2, T &result)
template<typename T >
T vecMul (const T &v1, typename VectorTraits< T >::BaseType v2)
Perform multiplication of v1 by scalar value v2, returning a new vector.
template<typename T >
void vecMul (const T &v1, typename VectorTraits< T >::BaseType v2, T &result)
template<typename T >
T vecMul (const T &v1, const T &v2)
Multiplies v1 by v2, returning a new vector.
template<typename T >
void vecMul (const T &v1, const T &v2, T &result)
template<typename T >
T vecDiv (const T &v1, typename VectorTraits< T >::BaseType v2)
Division by a scalar returning a new vector.
template<typename T >
void vecDiv (const T &v1, typename VectorTraits< T >::BaseType v2, T &result)
template<typename T >
T vecDiv (const T &v1, const T &v2)
Component-wise division of v1 by v2 returning a new vector.
template<typename T >
void vecDiv (const T &v1, const T &v2, T &result)
template<typename T >
VectorTraits< T >::BaseType vecDot (const T &v1, const T &v2)
Returns the dot product of v1 and v2.
template<typename T >
VectorTraits< T >::BaseType vecLength2 (const T &v)
Returns the squared length of v.
template<typename T >
VectorTraits< T >::BaseType vecLength (const T &v)
Returns the length of v.
template<typename T >
void vecNormalize (T &v)
Normalizes v in place. If the length of v is zero then has no effect.
template<typename T >
VectorTraits< T >::BaseType vecDistance2 (const T &v1, const T &v2)
Returns the distance squared between v1 and v2.
template<typename T >
VectorTraits< T >::BaseType vecDistance (const T &v1, const T &v2)
Returns the distance between v1 and v2.
template<typename T , typename S >
S vecConvert (const T &v)
Converts from one vector type to another.
template<typename T , typename S >
void vecConvert (const T &v1, S &v2)
Converts from one vector type to another.
template<typename T >
T vecConstruct (const typename VectorTraits< T >::BaseType *components)
template<typename T >
T vecCross (const T &v1, const T &v2)
Returns the cross product of v1 and v2, which must be 3-dimensional vectors.
IE_CORE_DECLAREPTR (VisibleRenderable)
IE_CORE_DECLAREPTR (WarpOp)
IE_CORE_FORWARDDECLARE (Writer)
IE_CORE_DECLAREPTR (YUVImageWriter)
def registerRunTimeTyped
This function adds the necessary function definitions to a python class for it to properly implement the RunTimeTyped interface.
def registerObject
def setLogLevelByName
Set the environment variable and the current LevelFilteredMessageHandler.
def setLogLevel
Set the environment variable and the current LevelFilteredMessageHandler.
def showCallStack
Help function to track dificult errors.
def exceptionInfo
Use this function to get information about the context where the exception happened.
def debugException
Sends debug messages to the current message handler and appends a full description of the catched exception.
def debug
Sends debug messages to the current message handler.
def warning
def info
def error
def isSimpleDataType
Utility function that recognizes objects that are simple types.
def isSimpleNumericDataType
Utility function that recognizes objects that are numeric simple types.
def isMatrixDataType
Utility function that recognizes objects that hold values as matrices.
def isMappingDataType
Utility function that returns ``True`` if a Data object obj could be created with a dict.
def isSequenceDataType
Utility function that returns ``True`` if a Data object obj could be created from a list.
def getDataDerivedTypes
Function that returns a list of Data derived classes.
def elementTypeFromDataType
Returns the type (class) for the element type hold on the instances of the given Data type.
def valueTypeFromSequenceType
Returns the type (class) used on each indexed value on the given sequence type.
def dataTypeFromElementType
Returns the Data class that is instantiable given an element type.
def dataTypeFromElement
Returns the Data class that is instantiable given a element data object.
def dataFromElement
Factory function for Data objects given its element data.
def mv
Moves the set of files specified by sequence1 to the set of files specified by sequence2, where sequence1 and sequence2 are FileSequence objects of equal length.
def cp
Copies the set of files specified by sequence1 to the set of files specified by sequence2, where sequence1 and sequence2 are FileSequence objects of equal length.
def rm
Removes all the files specified by the sequence.
def cat
Concetenates all the files specified by the sequence to stdout.
def formatParameterHelp
This function formats helpful descriptions of parameters, using a Formatter object.
def curry
Curries a function and a bunch of arguments - that is it creates a new function with the arguments baked in, so they don't need to be passed when the function is called.
def __object__deepcopy__
def loadConfig
This function provides an easy means of providing a flexible configuration mechanism for any software.
template<>
Imath::V3f convert (const RtPoint &from)
template<>
Imath::Color3f convert (const RtColor &from)
template<>
Imath::Box3f convert (const RtBound &from)
void convert (const Imath::M44f &from, RtMatrix to)
Conversions to RI types can't return the type, as typically they're typedefs for arrays.
void convert (const Imath::Box3f &from, RtBound to)
DataPtr convert (const char *data, RxInfoType_t type, RtInt count)
template<>
Imath::V2f convert (const DD::Image::Vector2 &from)
template<>
Imath::V2f convert (const DD::Image::Vector3 &from)
Discards from.z.
template<>
DD::Image::Vector3 convert (const Imath::V3f &from)
template<>
DD::Image::Vector3 convert (const Imath::V3d &from)
template<>
Imath::V2f convert (const DD::Image::Vector4 &from)
Discards from.z and from.w.
template<>
Imath::M44f convert (const DD::Image::Matrix4 &from)
template<>
Imath::Box2i convert (const DD::Image::Box &from)
template<>
DD::Image::Box3 convert (const Imath::Box3f &from)
template<>
std::string convert (const MString &from)
template<>
MString convert (const std::string &from)
template<>
Imath::V3f convert (const MVector &from)
template<>
Imath::V3f convert (const MFloatVector &from)
template<>
Imath::V3f convert (const MPoint &from)
template<>
Imath::V3f convert (const MFloatPoint &from)
template<>
MVector convert (const Imath::Color3f &from)
template<>
Imath::Color3f convert (const MColor &from)
template<>
MColor convert (const Imath::Color4f &from)
template<>
Imath::Box3f convert (const MBoundingBox &from)
template<>
Imath::Quatf convert (const MQuaternion &from)
template<>
MQuaternion convert (const Imath::Quatf &from)
template<>
MQuaternion convert (const Imath::Quatd &from)
template<>
Imath::M44f convert (const MMatrix &from)
template<>
Imath::Eulerf convert (const MEulerRotation &from)
template<>
MEulerRotation convert (const Imath::Eulerf &from)
template<>
MEulerRotation convert (const Imath::Eulerd &from)
template<>
IECore::TransformationMatrixf convert (const MTransformationMatrix &from)
template<>
MTransformationMatrix convert (const IECore::TransformationMatrixf &from)
template<>
IECore::DataPtr convert (const MCommandResult &from)
template<>
MDistance convert (const double &from)
template<>
double convert (const MDistance &from)
template<>
double convert (const MAngle &from)
template<>
double convert (const MTime &from)
template<>
MDistance convert (const float &from)
IE_CORE_FORWARDDECLARE (Primitive)
template<>
Imath::V3f convert (const UT_Vector3 &from)
template<>
Imath::V3f convert (const UT_Vector4 &from)
template<>
Imath::Box3f convert (const UT_BoundingBox &from)
Variables
__nextDynamicRunTimeTypedId = None
list __all__
dictionary __dataTypesConversionDict
dictionary __formatters
Detailed Description
This namespace contains all components of the core library.
Specialising in the IECore namespace. This is OK because the Nuke types will never be referenced in IECore. And it means that all the convert<> functions are in one namespace.
Specialising in the IECore namespace. This is OK because the Maya types will never be referenced in IECore
Specialising in the IECore namespace. This is OK because the Houdini types will never be referenced in IECore
Typedef Documentation
typedef TypedData< CompoundDataMap > IECore::CompoundDataBase
A subclass of Data which stores a map of other named Data objects - a CompoundDataMap. This is accessible as usual via the readable() and writable() member functions. Generally you wouldn't use this typedef directly, but instead use the CompoundData derived class which provides several useful utility methods.
Enumeration Type Documentation
enum IECore::TypeId
Enumerator:
UIntDataTypeId
Obsolete: LongData has been removed. The typeId remains for compatibility with old files, which now load as IntData.
CompoundDataTypeId
Obsolete: LongVectorData has been removed. The typeId remains for compatibility with old files, which now load as IntVectorData.
enum IECore::Winding
An enum used to specify the winding order of polygons.
Function Documentation
template<class T > T IECore::angle4D (const Imath::Quat< T > & q1, const Imath::Quat< T > & q2) [inline]
This is copied from the Imath corresponding to OpenEXR 1.6.1. It (and the other copied functions below) can be removed when we're no longer building against 1.4.0.
Referenced by slerp().
template<typename T > T IECore::asBigEndian (const T & x) [inline]
If running on a little endian platform, returns a copy of x with reversed bytes, otherwise returns x unchanged.
References littleEndian(), and reverseBytes().
template<typename T > T IECore::asLittleEndian (const T & x) [inline]
If running on a big endian platform, returns a copy of x with reversed bytes, otherwise returns x unchanged.
References bigEndian(), and reverseBytes().
template<typename T , typename S > T* IECore::assertedStaticCast (S * src) [inline]
Equivalent to static_cast, but using the type identifaction system implemented in RunTimeTyped to fire an assert if the equivalent runTimeCast would not succeed. In a non-asserted build this will compile directly down to a single static_cast.
template<typename T , typename S > IntrusivePtr<T> IECore::assertedStaticCast (const IntrusivePtr< S > & src) [inline]
Equivalent to staticPointerCast, but using the type identifaction system implemented in RunTimeTyped to fire an assert if the equivalent runTimeCast would not succeed. In a non-asserted build this will compile directly down to a single staticPointerCast.
template<typename Vec , typename F > void IECore::bezierSubdivide (const Vec & v0, const Vec & v1, const Vec & v2, const Vec & v3, typename Vec::BaseType tolerance, F & f) [inline]
Templated implementation of De Casteljau's algorithm. Calls the functor f for points on the bezier curve defined by v0 - v3, progressing from the point at t==0 to the point at t==1. Level of subdivision is controlled by the tolerance parameter, which defines approximately how far from the true curve a point is allowed to stray.
bool IECore::bigEndian () [inline]
Returns true if running on a big endian platform.
Referenced by asLittleEndian().
template<typename T > bool IECore::boxIntersects (const T & box, const typename BoxTraits< T >::BaseType & origin, const typename BoxTraits< T >::BaseType & direction, typename BoxTraits< T >::BaseType & result) [inline]
Intersects the box with the given ray. The direction vector must be normalissed. Returns true if there was an intersection, setting the "result" argument with the point of intersection accordingly.
template<> Imath::V3d IECore::convert (const DD::Image::Vector4 & from) [inline]
Discards from.z and from.w.
Discards from.w.
DataPtr IECore::convert (const char * data, RxInfoType_t type, RtInt count)
This function is intended for converting the results of RxAttribute and RxOption into useful IECore types.
template<typename T , typename F > T IECore::convert (const F & from) [inline]
The convert function is used to provide easy conversion between simple types (like vectors) in IECore, Imath and other libraries. It should be specialised appropriately in support libraries.
Todo:
Could this be declared static inline?
template<class Vec , class Rand > Vec IECore::cosineHemisphereRand (Rand & rand) [inline]
Returns a random point uniformly distributed on a hemisphere of unit radius where z>0 for all points.
def IECore::curry (bakeArgs, bakeKwds)
Curries a function and a bunch of arguments - that is it creates a new function with the arguments baked in, so they don't need to be passed when the function is called.
template<template< typename > class Trait> bool IECore::despatchTraitsTest (const DataPtr & data) [inline]
Simply returns the result of Trait - this can be used to check TypeTraits at runtime. e.g. bool isSimple = despatchTraitsTest<TypeTraits::IsSimpleTypedData>(data).
template<class Functor > Functor::ReturnType IECore::despatchTypedData (const DataPtr & data) [inline]
Convenience version of despatchTypedData which operates on all TypedData classes, constructs the ErrorHandler and Functor using their default constructors, and throws an InvalidArgumentException when data which isn't TypedData is encountered.
template<class Functor > Functor::ReturnType IECore::despatchTypedData (const DataPtr & data, Functor & functor) [inline]
Convenience version of despatchTypedData which operates on all TypedData classes, and constructs an ErrorHandler using its default constructor
template<class Functor , template< typename > class Enabler> Functor::ReturnType IECore::despatchTypedData (const DataPtr & data) [inline]
Convenience version of despatchTypedData, which throws an InvalidArgumentException when data which doesn't match the Enabler is encountered.
template<class Functor , template< typename > class Enabler> Functor::ReturnType IECore::despatchTypedData (const DataPtr & data, Functor & functor) [inline]
Convenience version of despatchTypedData, which throws an InvalidArgumentException when data which doesn't match the Enabler is encountered
template<class Functor , template< typename > class Enabler, typename ErrorHandler > Functor::ReturnType IECore::despatchTypedData (const DataPtr & data, Functor & functor, ErrorHandler & errorHandler) [inline]
Given a DataPtr which points to one a instance of the TypedData classes, call the operator() member function on an instance of Functor, passing the DataPtr downcast to the correct type. A template parameter, Enabler, allows the function to run only on certain subsets of TypedData, for example, only VectorTypeData. The template specified here should be compatible with boost::mpl - see examples in TypeTraits.h.
When an instance of a type not supported by the Enabler is encountered, the ErrorHandler is called. An ErrorHandler class should take the following form:
 struct EH
 {
     template<typename DataType, typename Functor>
     void operator()( typename DataType::ConstPtr , const Functor& )
     {
         // Handle error here
     }
 };
A Functor should look this like:
 struct F
{
        typedef unspecified-type ReturnType;
        template<typename T>
        ReturnType operator()( typename T::Ptr data )
        {
         // Deal with the data and, optionally, return some value
        }
};
Example uses can be found it the ImageWriter-derived classes
void IECore::findSequences (const std::vector< std::string > & names, std::vector< FileSequencePtr > & sequences, size_t minSequenceSize)
Returns a list of FileSequence objects representing all the sequences in names. names is just a list of arbitrary strings, which may or may not represent files on disk. The returned sequences have at least the minSequenceSize elements.
void IECore::findSequences (const std::vector< std::string > & names, std::vector< FileSequencePtr > & sequences)
Returns a list of FileSequence objects representing all the sequences in names. names is just a list of arbitrary strings, which may or may not represent files on disk. The returned sequences have at least 2 elements.
FrameListPtr IECore::frameListFromList (const std::vector< FrameList::Frame > & frames)
Returns a FrameList instance that "best" represents the specified list of integer frame numbers. This function attempts to be intelligent and uses a CompoundFrameList of FrameRange objects to represent the specified frames compactly.
template<class String > bool IECore::isLowerCase (const String & s) [inline]
Returns true if s has no upper case letters and at least one lower case letter - non alphabetic characters are ignored.
template<class String > bool IECore::isUpperCase (const String & s) [inline]
Returns true if s has no lower case letters and at least one upper case letter - non alphabetic characters are ignored.
template<class T > SphericalHarmonics<T> IECore::lambertianKernel (unsigned int bands, bool normalized = false) [inline]
Creates a SphericalHarmonics kernel that represents the lambert cosine rule From "On the Relationship between Radiance and Irradiance: Determining the illumination from images of a convex Lambertian object" by by Ramamoorthi, Ravi and Hanrahan, Pat - 2001.
bool IECore::littleEndian () [inline]
Returns true if running on a little endian platform.
Referenced by asBigEndian().
template<typename T > T::BaseType IECore::luminance (const T & color) [inline]
The weights used by this function are those defined by ITU-R Recommendation BT.709. See http://www.faqs.org/faqs/graphics/colorspace-faq/ section C-9
template<typename T > Imath::Matrix44<T> IECore::matrixFromBasis (const Imath::Vec3< T > & x, const Imath::Vec3< T > & y, const Imath::Vec3< T > & z, const Imath::Vec3< T > & o) [inline]
Returns a matrix specified by the orientation of the unit vectors x,y,z and origin o after transformation by the matrix.
void IECore::msg (MessageHandler::Level level, const std::string & context, const std::string & message)
Free functions which calls MessageHandler::output() with their arguments. These are provided for brevity.
template<typename Iterator > std::iterator_traits<Iterator>::value_type IECore::polygonNormal (Iterator first, Iterator last) [inline]
Returns the normalized normal for the polygon specified by the 3D vertices in the given iterator range. Copes properly with concave polygons. Assumes a righthanded (counter-clockwise) winding order, meaning that the normal will face towards an observer who sees the loop from first to last as being counter-clockwise.
template<typename Iterator > Winding IECore::polygonWinding (Iterator first, Iterator last, const typename std::iterator_traits< Iterator >::value_type & viewVector) [inline]
Returns the winding order for the polygon specified by the 3D vertices in the given iterator range, when viewed with the specified view vector. Copes correctly with concave polygons.
template<typename Iterator > Winding IECore::polygonWinding (Iterator first, Iterator last) [inline]
Returns the winding order for the polygon specified by the 2D vertices in the given iterator range. Copes correctly with concave polygons.
def IECore::registerRunTimeTyped (typ, typId = None, baseClass = None)
This function adds the necessary function definitions to a python class for it to properly implement the RunTimeTyped interface.
It should be called once for all python classes inheriting from RunTimeTyped. It also calls registerTypeId() for you. baseClass is deprecated.
Todo:
Remove deprecation warning and baseClass parameter on Cortex 6. typId is optional and if not defined, this function will associate a dynamic Id in the range FirstDynamicTypeId and LastDynamicTypeId from TypeIds.h. It's necessary to specify type Id for Object derived class or anything that is serializable.
template<class T > SphericalHarmonics<T> IECore::rotatedKernel (const SphericalHarmonics< T > & kernel, const Imath::V3f & direction) [inline]
Creates a SphericalHarmonics object by pointing a given SH kernel to a given direction. The rotation is a lot faster than SHRotation because it takes in consideration the kernel symmetries on the Z axis. Based on "Real-time Soft Shadows in Dynamic Scenes using Spherical Harmonic Exponentiation" by Zhong Ren and Rui Wang and John Snyder and Kun Zhou and Xinguo Liu and Bo Sun and Peter-pike Sloan and Hujun Bao and Qunsheng Peng and Baining Guo - 2006.
template<typename T , typename S > T* IECore::runTimeCast (S * src) [inline]
Equivalent to dynamic_cast but using the type identification system implemented in RunTimeTyped. This should be used in preference to dynamic_cast wherever possible.
template<typename T , typename S > IntrusivePtr<T> IECore::runTimeCast (const IntrusivePtr< S > & src) [inline]
Equivalent to boost::dynamicPointerCast but using the type identification system implemented in RunTimeTyped. This should be used in preference to both dynamic_cast and dynamicPointerCast wherever possible.
template<class T > T IECore::sinx_over_x (T x) [inline]
This is copied from the Imath corresponding to OpenEXR 1.6.1. It (and the other copied functions below) can be removed when we're no longer building against 1.4.0.
Referenced by slerp().
template<class T > Imath::Quat<T> IECore::slerp (const Imath::Quat< T > & q1, const Imath::Quat< T > & q2, T t) [inline]
This is copied from the Imath corresponding to OpenEXR 1.6.1. It is much more stable than the one in OpenEXR 1.4.0 so we take a copy of the preferred one while we're still building with the old OpenEXR.
References angle4D(), and sinx_over_x().
Referenced by slerpShortestArc().
template<class T > Imath::Quat<T> IECore::slerpShortestArc (const Imath::Quat< T > & q1, const Imath::Quat< T > & q2, T t) [inline]
This is copied from revision 1.7 of IlmBase/Imath/ImathQuat.h in the OpenEXR cvs repository. It's useful and it's not available in any of the official OpenEXR releases yet.
References slerp().
template<template< typename > class Predicate> bool IECore::testTypedData (DataPtr data) [inline]
Returns true if the passed data matches the given predicate, else return false. For example testTypedData< TypeTraits::IsVectorTypedData >(new DoubleVectorData()) would return true, while testTypedData< TypeTraits::IsSimpleTypedData >(new DoubleVectorData()) would return false.
template<typename Vec > void IECore::tetrahedronBarycentric (const Vec & v0, const Vec & v1, const Vec & v2, const Vec & v3, const Vec & p, typename VectorTraits< Vec >::BaseType barycentric[4]) [inline]
Returns the barycentric coordinates of the given point relative to the tetrahedron. The point is assumed to be inside the tetrahedron.
Imath::V3i IECore::tetrahedronFaceIndices (int face) [inline]
A tetrahedron has 4 faces, each of which is triangle. This function returns the vertex indices which make up the triangle on the specified face.
template<class Vec > VectorTraits<Vec>::BaseType IECore::triangleArea (const Vec & v0, const Vec & v1, const Vec & v2) [inline]
Todo:
It might be nice to make a triangle class and make these methods.
template<class Vec > int IECore::triangleBarycentricFeature (const Vec & barycentric, typename VectorTraits< Vec >::BaseType tolerance = 1.e-6) [inline]
Returns information regarding the feature region of a barycentric coordinate on the triangle.
0 is the area within the triangle itself
1 is the edge connecting v1 and v2
2 is vertex v2
3 is the edge connecting v0 and v2
4 is vertex v0
5 is the edge connecting v0 and v1
6 is vertex v1
template<class Vec > Vec IECore::triangleNormal (const Vec & v0, const Vec & v1, const Vec & v2) [inline]
Returns the normal for the specified triangle. Winding order is considered to be counter-clockwise as with the rest of cortex - the normal will face towards a viewer who sees the loop v0->v1->v2->v0 as being counter-clockwise.
template<class Vec > bool IECore::triangleRayIntersection (const Vec & v0, const Vec & v1, const Vec & v2, const Vec & origin, const Vec & dir, Vec & pt, Vec & barycentric, bool & front) [inline]
Returns true if the ray hits the triangle. Also fills pt, barycentric and front in the same way as Imath::intersect() This function treats the ray as finite on the origin and infinite on the other end and Imath::intersect considers both ends to be infinite.
template<typename T > void IECore::vecAdd (const T & v1, const T & v2, T & result) [inline]
Adds v1 to v2, placing the result in result. It is safe for result to be the same as either v1 or v2 to peform addition in place.
template<typename T > T IECore::vecConstruct (const typename VectorTraits< T >::BaseType * components) [inline]
Constructs a new vector and returns it. The components array must be at least VectorTraits<T>::dimensions() long.
template<typename T > void IECore::vecDiv (const T & v1, const T & v2, T & result) [inline]
Component-wise division of v1 by v2 placing the result in result. It is safe for result to be the same as either v1 or v2 to perform division in place.
template<typename T > void IECore::vecDiv (const T & v1, typename VectorTraits< T >::BaseType v2, T & result) [inline]
Division by a scalar placing the result in result. It is safe for result to be the same as v1 to perform division in place.
template<typename T > void IECore::vecMul (const T & v1, const T & v2, T & result) [inline]
Multiplies v1 by v2, placing the result in result. It is safe for result to be the same as either v1 or v2 to perform multiplication in place.
template<typename T > void IECore::vecMul (const T & v1, typename VectorTraits< T >::BaseType v2, T & result) [inline]
Perform multiplication of v1 by scalar value v2, placing the result in result. It is safe for result to be the same as v1 to perform multiplication in place.
template<typename T > void IECore::vecSub (const T & v1, const T & v2, T & result) [inline]
Subtracts v2 from v1, placing the result in result. It is safe for result to be the same as either v1 or v2 to perform subtraction in place.
template<class T > void IECore::windowingFilter (SphericalHarmonics< T > & sh, float windowSize) [inline]
Applies windowing filter to attenuate "ringing" artifacts. Based on "Real-time Soft Shadows in Dynamic Scenes using Spherical Harmonic Exponentiation" by Zhong Ren and Rui Wang and John Snyder and Kun Zhou and Xinguo Liu and Bo Sun and Peter-pike Sloan and Hujun Bao and Qunsheng Peng and Baining Guo - 2006. The authors suggest using windowSize = 2*bands
Variable Documentation
list IECore::__all__
Initial value:
[ "setLogLevelByName", "setLogLevel", "showCallStack",
                "exceptionInfo", "debugException", "debug", "warning", "info", "error",
]
dictionary IECore::__formatters
Initial value:
{
        IECore.CompoundParameter : __formatCompoundParameter,
        IECore.FloatParameter : __formatNumericParameter,
        IECore.DoubleParameter : __formatNumericParameter,
        IECore.IntParameter : __formatNumericParameter,
        IECore.FileNameParameter : __formatFileNameParameter,
        IECore.DirNameParameter : __formatDirNameParameter,
        IECore.FileSequenceParameter : __formatFileSequenceParameter,
}