parameters:
  name: ''
  vmImage: ''
  container: ''
  buildType: 'RELEASE'
  threads: 2
  options: ''
  vcvarsallPath: 

jobs:

 - job: ${{ parameters.name }}_${{ parameters.buildType }}

   timeoutInMinutes: 360

   ${{ if ne(parameters.container, '') }}:
      container: ${{ parameters.container }}

   pool:
     vmImage: ${{ parameters.vmImage }}

   variables:
     BUILD_TYPE: ${{ parameters.buildType }}

   steps:

   - task: UsePythonVersion@0
     inputs:
       versionSpec: '2.7'
       addToPath: true
       architecture: 'x64'
     condition: eq( variables['Agent.OS'], 'Windows_NT' )

   - script: python -m pip install scons
     displayName: Install Scons (Windows)
     condition: eq( variables['Agent.OS'], 'Windows_NT' )

   # Provides $(Cortex.*) variables
   - script: |
       python config/azure/setBuildVars.py
     displayName: 'Set Custom Variables'

   - script: |
       python config/installDependencies.py $(Cortex.Dependencies.Dir)
     displayName: 'Install Dependencies'

   - script: |
       export LD_PRELOAD=/usr/lib64/libSegFault.so
     displayName: 'Configure Toolchain (Linux)'
     condition: eq( variables['Agent.OS'], 'Linux' )

   - script: |
       brew update &&
       brew install scons doxygen
     displayName: 'Install Toolchain (Darwin)'
     condition: eq( variables['Agent.OS'], 'Darwin' )
   
   # Windows needs the vcvarsall.bat command in the same script to retain environment variables for the scons task
   - script: |
       call ${{ parameters.envSetupCmd }}
       scons -j ${{ parameters.threads }} install BUILD_TYPE=${{ parameters.buildType }} OPTIONS=${{ parameters.options }}
     displayName: 'Build (Windows)'
     condition: eq( variables['Agent.OS'], 'Windows_NT' )

   - script: |
       g++ --version
       scons -j ${{ parameters.threads }} install BUILD_TYPE=${{ parameters.buildType }} OPTIONS=${{ parameters.options }}
     displayName: 'Build (POSIX)'
     condition: or( eq( variables['Agent.OS'], 'Darwin' ), eq( variables['Agent.OS'], 'Linux' ) )

   - script: |
       scons testCore testCorePython testScene testImage testAlembic testAppleseed OPTIONS=${{ parameters.options }}
       cat test/IECore/results.txt
     displayName: 'Test (POSIX)'
     condition: and( succeeded(), or( eq( variables['Agent.OS'], 'Darwin' ), eq( variables['Agent.OS'], 'Linux' ) ) )

   - publish: $(Cortex.Build.Name)
     artifact: $(Cortex.Build.Name)



