#!/usr/bin/env python2.6

import IEEnv
import subprocess
import sys
import os
import os.path
import shutil

def build( extraArgs = [] ) :
	
	buildArgs = [ "INSTALL_PREFIX=/software" ]
	buildArgs.extend( extraArgs )
	buildArgs.extend( sys.argv[1:] )	
	
	if subprocess.call( [ "scons" ] + buildArgs ) != 0 :
	
		raise RuntimeError("Error : scons " + str( " ".join( buildArgs ) ) )
		
	if subprocess.call( [ "scons", "install" ] + buildArgs ) != 0 :
	
		raise RuntimeError("Error : scons install " + str( " ".join( buildArgs ) ) )

def installDocs() :
	
	buildArgs = [ "INSTALL_PREFIX=/software" ]
	
	if subprocess.call( [ "scons", "installDoc" ] + buildArgs ) != 0 :
	
		raise RuntimeError("Error : scons installDoc " + str( " ".join( buildArgs ) ) )

if IEEnv.platformOS() == "osx104" or IEEnv.platformOS() == "osx105" :
	
	if os.path.exists( ".sconsign.dblite" ) :
		
		os.remove( ".sconsign.dblite" )
		
	if os.path.exists( ".sconf_temp" ) :
		
		shutil.rmtree( ".sconf_temp" )	
		
	build()
	
	installDocs()

elif IEEnv.platform() == "cent5.x86_64" :

	build( [ "COMPILER_VERSION=4.1.2", "DL_VERSION=9.0.103", "PYTHON_VERSION=2.6" ] )
	build( [ "COMPILER_VERSION=4.1.2", "DL_VERSION=9.0.111", "PYTHON_VERSION=2.6" ] )
	build( [ "COMPILER_VERSION=4.1.2", "DL_VERSION=9.0.132", "PYTHON_VERSION=2.6" ] )
	build( [ "COMPILER_VERSION=4.1.2", "DL_VERSION=10.0.7", "PYTHON_VERSION=2.6" ] )
	build( [ "APP=maya", "APP_VERSION=2010", "DL_VERSION=9.0.111" ] )
	build( [ "APP=maya", "APP_VERSION=2011", "DL_VERSION=9.0.111" ] )
	build( [ "APP=maya", "APP_VERSION=2012", "DL_VERSION=9.0.111" ] )
	build( [ "APP=nuke", "APP_VERSION=6.2v4" ] )
	build( [ "APP=nuke", "APP_VERSION=6.3v1" ] )
	build( [ "APP=nuke", "APP_VERSION=6.3v2" ] )
	build( [ "APP=houdini", "APP_VERSION=11.0.775" ] )
	build( [ "APP=houdini", "APP_VERSION=11.1.22" ] )
	
	installDocs()

else :

	raise RuntimeError( "Unknown platform" )

